const statusClass=s=>['done','active','queued','blocked','rejected'].includes(s)?s:'queued';
const progress=n=>n.progress??(n.status==='done'?100:n.status==='active'?50:0);
let DATA,allNodes={};
mermaid.initialize({startOnLoad:false,theme:'dark',securityLevel:'loose'});
function agentGraph(){return ['flowchart TB','H[Human PI] --> A[Astra controller]','A --> F[Formulation lead]','A --> L[Literature lead]','A --> N[Numerics lead]','A --> U[Audit lead]','F --> P[DeepSeek Flash pool]','L --> P','N --> P','U --> P','P --> E[artifacts and metrics]'].join('\n')}
function researchGraph(v){const a=['flowchart LR','classDef done fill:#164d3a,stroke:#39d98a,color:#edf3ff','classDef active fill:#173d73,stroke:#62a5ff,color:#edf3ff','classDef queued fill:#4a3a15,stroke:#ffca5c,color:#edf3ff','classDef blocked fill:#552237,stroke:#ff6e86,color:#edf3ff'];DATA.groups.filter(g=>v==='all'||g.id===v).forEach(g=>{a.push('subgraph '+g.id+'['+g.label+']');g.nodes.forEach(n=>a.push(n.id+'["'+n.id+' · '+n.label+'<br/>'+n.status+' · '+progress(n)+'%<br/>'+n.hours+'h · ETA '+n.eta_days+'d"]:::'+statusClass(n.status)));g.nodes.forEach(n=>(n.depends_on||[]).forEach(d=>a.push(d+' --> '+n.id)));a.push('end')});if(v==='all')DATA.cross_group_edges.forEach(e=>a.push(e.from+' -. '+e.kind+' .-> '+e.to));return a.join('\n')}
function showNode(id){const n=allNodes[id];if(n)document.getElementById('detail').textContent=[n.id+' · '+n.label,'Group: '+n.group.label,'Status: '+n.status+' · progress '+progress(n)+'%','Agent-hours: '+n.hours+' · ETA: '+n.eta_days+' days','Artifact: '+n.artifact,'Depends on: '+((n.depends_on||[]).join(', ')||'none'),'Validation: '+(n.validation_status||'pending')].join('\n')}
function showGroup(g){document.getElementById('detail').textContent=[g.label,'','Direction: '+g.direction,'Lead: '+g.lead,'Status: '+g.status+' · confidence '+g.confidence,'Agents: '+g.active_agents,'Agent-hours: '+g.spent_agent_hours+'/'+g.budget_agent_hours,'ETA: '+g.eta_days_low+'–'+g.eta_days_high+' days'].join('\n')}
async function draw(id,src){const box=document.getElementById(id);try{const x=await mermaid.render('m'+Date.now(),src);box.innerHTML=x.svg;box.querySelectorAll('.node').forEach(e=>{e.title='Hover for details';e.onmouseenter=()=>showNode(e.id.replace(/^flowchart-/,'').split('-')[0])})}catch(e){box.textContent='Mermaid parse error: '+e.message}}
function render(v){draw('researchDag',researchGraph(v));const gs=DATA.groups.filter(g=>v==='all'||g.id===v);document.getElementById('cards').innerHTML=gs.map(g=>'<div class="card" data-g="'+g.id+'"><div class="row"><b>'+g.label+'</b><span class="'+statusClass(g.status)+'">'+g.status+'</span></div><div class="small">'+g.direction+'</div><div class="bar"><i style="width:'+Math.min(100,Math.round(100*g.spent_agent_hours/Math.max(1,g.budget_agent_hours)))+'%"></i></div><div class="row small"><span>'+g.active_agents+' agents · '+g.spent_agent_hours+'/'+g.budget_agent_hours+'h</span><span>ETA '+g.eta_days_low+'–'+g.eta_days_high+'d</span></div></div>').join('');document.querySelectorAll('.card').forEach(e=>e.onclick=()=>showGroup(DATA.groups.find(g=>g.id===e.dataset.g)));document.getElementById('agents').textContent=gs.reduce((x,g)=>x+g.active_agents,0);document.getElementById('hours').textContent=gs.reduce((x,g)=>x+g.spent_agent_hours,0);document.getElementById('progress').textContent=Math.round(100*gs.reduce((x,g)=>x+g.spent_agent_hours,0)/Math.max(1,gs.reduce((x,g)=>x+g.budget_agent_hours,0)))+'%';document.getElementById('eta').textContent=gs.length?Math.min(...gs.map(g=>g.eta_days_low))+'–'+Math.max(...gs.map(g=>g.eta_days_high))+'d':'—'}
fetch('research_map.json').then(r=>r.json()).then(d=>{DATA=d;d.groups.forEach(g=>g.nodes.forEach(n=>allNodes[n.id]=Object.assign({},n,{group:g})));draw('agentDag',agentGraph());render('all');document.querySelectorAll('button[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('button[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)})});
