#!/usr/bin/env python3
"""W098-CLASSSEP-PROSE-SHADOW-01 — read-only shadow test of the proposed
classsep prose-precision patch (artifacts/formulation/proposals/classsep_prose_precision_patch.md,
sha256 edeb6588a17b31cf2c7fe68b28fbb28ab2b8667cad01d1e5b270ecc91eae9e96).

The instrument:
  1. verifies every pin in pre_registration.json against disk;
  2. snapshots research_map/research_map.json (moving target) and the canonical detector;
  3. generates the shadow module from the canonical bytes by applying ONLY the patch's
     insertions, and difflib-verifies that the diff contains no deletions and exactly the
     three expected change regions;
  4. runs canonical vs shadow on: the 27-fixture worker-07 corpus, the proposal's own
     4 FP + 2 TP probes, 6 adversarial over-suppression probes, a 10-string
     declaration-mode parity battery, the frozen map snapshot (map + done-node artifacts,
     replicating audit_evidence.py's route rule), and a 3-probe growth experiment;
  5. writes raw per-probe JSON and report.json.

No canonical path is written. No network. Deterministic. Exit 0 = run VALID (not a verdict).
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import re
import sys
import difflib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]          # repo root (…/ai4math-swarm)
HERE = Path(__file__).resolve().parent
SNAP = HERE / "snapshot"
RAW = HERE / "raw"
PRE = json.loads((HERE / "pre_registration.json").read_text())
PINS = PRE["pins"]


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def sha256_file(p: Path) -> str:
    return sha256_bytes(p.read_bytes())


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


# ---------------------------------------------------------------- pin verification
pin_report = {}
for key in ("canonical_detector", "patch_proposal", "regression_harness",
            "worker07_corpus_results", "audit_evidence"):
    p = ROOT / PINS[key]["path"]
    got = sha256_file(p) if p.is_file() else None
    pin_report[key] = {"path": PINS[key]["path"], "expected": PINS[key]["sha256"],
                       "measured": got, "match": got == PINS[key]["sha256"]}
    if got != PINS[key]["sha256"]:
        print(f"PIN MISMATCH {key}: expected {PINS[key]['sha256']} got {got}")
        (RAW / "pin_report.json").write_text(json.dumps(pin_report, indent=2, sort_keys=True))
        sys.exit(2)

# ---------------------------------------------------------------- snapshots
SNAP.mkdir(exist_ok=True)
RAW.mkdir(exist_ok=True)
canon_bytes = (ROOT / PINS["canonical_detector"]["path"]).read_bytes()
(SNAP / "class_separation.canonical.py").write_bytes(canon_bytes)
map_bytes = (ROOT / "research_map/research_map.json").read_bytes()
(SNAP / "research_map.pinned.json").write_bytes(map_bytes)

# ---------------------------------------------------------------- shadow generation
PATCH_A_ANCHOR = ('_NEG_BEFORE_ASSERT = re.compile(r"(?:no|not|never|without|zero|absent|nor)\\s+'
                  '(?:\\w+\\s+){0,2}$", re.I)\n')
PATCH_A_ADD = PATCH_A_ANCHOR + '''
# --- shadow patch begin: classsep_prose_precision_patch.md (edeb6588a17b) ---
_SENT = re.compile(r"[^.!?]*[.!?]|[^.!?]*$")
_META = re.compile(
    r"\\b(?:pattern|token|label|test|case|corpus|fixture|probe|scanner|regex|"
    r"non-?merge|split|independent|discussed|quoted|flag(?:s|ged)?|match(?:es|ed)?\\s+only)\\b",
    re.I)


def _sentence_containing(text: str, pos: int) -> str:
    left = 0
    for mm in re.finditer(r"[.!?]", text[:pos]):
        left = mm.end()
    right = len(text)
    mm = re.search(r"[.!?]", text[pos:])
    if mm:
        right = pos + mm.end()
    return text[left:right]
# --- shadow patch end ---
'''

PATCH_B_ANCHOR = '''        if _BENIGN.search(t[max(0, m.start() - 8):m.end() + 8]):
            continue
'''
PATCH_B_ADD = PATCH_B_ANCHOR + '''        if mode == "prose":
            sent = _sentence_containing(t, m.start())
            if (_NEG_BEFORE_ASSERT.search(sent) or _PROHIBIT.search(sent)
                    or _SPLIT.search(sent) or _META.search(sent)):
                continue  # prose-mode sentence is metalinguistic or negative
'''

HEADER = ('"""SHADOW COPY generated by W098-CLASSSEP-PROSE-SHADOW-01 from\n'
          'research_map/class_separation.py#c266dbceca87 with only the insertions of\n'
          'artifacts/formulation/proposals/classsep_prose_precision_patch.md#edeb6588a17b applied.\n'
          'Not a canonical artifact; never import this from production paths."""\n')

canon_text = canon_bytes.decode()
if canon_text.count(PATCH_A_ANCHOR) != 1 or canon_text.count(PATCH_B_ANCHOR) != 1:
    print("PATCH ANCHORS NOT UNIQUE — aborting")
    sys.exit(2)
shadow_text = canon_text.replace(PATCH_A_ANCHOR, HEADER + PATCH_A_ADD).replace(PATCH_B_ANCHOR, PATCH_B_ADD)
shadow_path = HERE / "shadow_class_separation.py"
shadow_path.write_text(shadow_text)

diff = list(difflib.unified_diff(canon_text.splitlines(keepends=True),
                                 shadow_text.splitlines(keepends=True),
                                 fromfile="canonical", tofile="shadow"))
removed = [l for l in diff if l.startswith("-") and not l.startswith("---")]
added = [l for l in diff if l.startswith("+") and not l.startswith("+++")]
hang = [l for l in diff if l.startswith(("@@", " ", "-", "+"))]
replaced = sum(1 for l in diff if l.startswith("-") and not l.startswith("---"))
shadow_provenance = {
    "canonical_sha256": sha256_bytes(canon_bytes),
    "shadow_sha256": sha256_bytes(shadow_text.encode()),
    "diff_lines_added": len(added), "diff_lines_removed": len(removed),
    "removed_lines": removed, "hunks": sum(1 for l in diff if l.startswith("@@")),
    "only_insertions": len(removed) == 0,
}
(RAW / "shadow_provenance.json").write_text(json.dumps(shadow_provenance, indent=2, sort_keys=True))
if removed:
    print("UNEXPECTED DELETIONS in shadow diff — aborting")
    sys.exit(2)

canon = load_module("w098_canon_cs", SNAP / "class_separation.canonical.py")
shadow = load_module("w098_shadow_cs", shadow_path)

# ---------------------------------------------------------------- corpus battery
corpus = json.loads((ROOT / PINS["worker07_corpus_results"]["path"]).read_text())


def run_corpus(mod):
    rows = []
    tp = fp = tn = fn = 0
    for fx in corpus["fixtures"]:
        path = ROOT / fx["fixture_path"]
        if not path.exists():
            rows.append({"id": fx["id"], "class": "MISSING"}); continue
        m = json.loads(path.read_text())
        det = mod.findings_for_map(m)
        for g in m.get("groups", []):
            for n in g.get("nodes", []):
                art = n.get("artifact")
                if art and (ROOT / art).is_file():
                    det += mod.findings_for_text((ROOT / art).read_text(errors="replace"),
                                                 f"artifact {art}")
        got, truth = bool(det), bool(fx["is_class_merge"])
        if truth and got: tp += 1; cls = "TP"
        elif truth and not got: fn += 1; cls = "FN-MISSED"
        elif not truth and got: fp += 1; cls = "FP-SPURIOUS"
        else: tn += 1; cls = "TN"
        rows.append({"id": fx["id"], "class": cls, "surface": fx.get("surface"),
                     "first_finding": (det[0][:160] if det else "")})
    return {"tp": tp, "fn": fn, "tn": tn, "fp": fp,
            "verdict": "PASS" if fn == 0 and fp == 0 else "DEFECTIVE", "rows": rows}


corpus_canon = run_corpus(canon)
corpus_shadow = run_corpus(shadow)
(RAW / "corpus_canon.json").write_text(json.dumps(corpus_canon, indent=2, sort_keys=True))
(RAW / "corpus_shadow.json").write_text(json.dumps(corpus_shadow, indent=2, sort_keys=True))

# ---------------------------------------------------------------- probe batteries
FP_PROBES = [
    "so no C0/C2 merge exists at the formal surface.",
    "2 SPLIT_REQUIRED (TC-F0-N14 merged C0/C2 regularities; the two rows require a split)",
    "R1's merge pattern matches only bare C0/C2 composites",
    "This is a class separation check: independent C0/C2 non-merge evidence.",
]
TP_PROBES = [
    "The C0/C2 merged class is the right unit of analysis for this portfolio.",
    "This result covers the C0/C2 unified class.",
]
FN_PROBES = [
    ("FN1_meta_case", "The C0/C2 merged class is the only case we consider."),
    ("FN2_meta_test", "We test that the C0/C2 unified class is the right unit."),
    ("FN3_meta_corpus", "This corpus treats the C0/C2 as one class."),
    ("FN4_meta_independent", "The independent C0/C2 merged class is our unit of analysis."),
    ("FN5_meta_pattern", "The C0/C2 combined pattern is the portfolio's chosen unit."),
    ("FN6_neg_scope", "It is not the case that the classes are separate; the C0/C2 are one class."),
]
DECL_STRINGS = [
    "C0 or C2", "C2/C0", "the C0 and C2 classes", "AF-WCC-VAC-GEN", "no C0/C2 merge",
    "C0-vs-C2 distinction", "never write 'C0 or C2'", "merged C0/C2 class",
    "composite C0C2 regularity", "two separate classes C0, C2",
]


def probe_row(mod, text):
    out: list = []
    mod._scan_composite(text, "probe", out, mode="prose")
    return out


probes = {"fp": [], "tp": [], "fn": [], "declaration_parity": []}
for t in FP_PROBES:
    c, s = probe_row(canon, t), probe_row(shadow, t)
    probes["fp"].append({"text": t, "canonical": c, "shadow": s,
                         "canonical_fires": bool(c), "shadow_fires": bool(s),
                         "expected_shadow_fires": False,
                         "ok": (not s)})
for t in TP_PROBES:
    c, s = probe_row(canon, t), probe_row(shadow, t)
    probes["tp"].append({"text": t, "canonical": c, "shadow": s,
                         "canonical_fires": bool(c), "shadow_fires": bool(s),
                         "expected_shadow_fires": True,
                         "ok": bool(s)})
for name, t in FN_PROBES:
    c, s = probe_row(canon, t), probe_row(shadow, t)
    probes["fn"].append({"name": name, "text": t, "canonical": c, "shadow": s,
                         "canonical_fires": bool(c), "shadow_fires": bool(s),
                         "over_suppressed": bool(c) and not s,
                         "pre_registered_expectation": "shadow suppresses (over-suppression measured)"})
for t in DECL_STRINGS:
    co, so = [], []
    canon._scan_composite(t, "decl", co, mode="declaration")
    shadow._scan_composite(t, "decl", so, mode="declaration")
    probes["declaration_parity"].append({"text": t, "canonical": co, "shadow": so,
                                         "identical": co == so})
decl_parity_ok = all(r["identical"] for r in probes["declaration_parity"])
(RAW / "probes.json").write_text(json.dumps(probes, indent=2, sort_keys=True))

# ---------------------------------------------------------------- map battery
m = json.loads(map_bytes)
art_texts = {}
for g in m.get("groups", []):
    for n in g.get("nodes", []):
        art = n.get("artifact")
        if not art:
            continue
        p = ROOT / art
        if p.is_file() and p.stat().st_size < 2_000_000:
            try:
                art_texts[art] = p.read_text(errors="replace")
            except OSError:
                pass


def map_hard(mod):
    hard = [it for it in mod.findings_for_map(m) if not str(it).startswith("CLASSSEP-SOFT:")]
    soft = [it for it in mod.findings_for_map(m) if str(it).startswith("CLASSSEP-SOFT:")]
    for g in m.get("groups", []):
        for n in g.get("nodes", []):
            art = n.get("artifact")
            if art in art_texts:
                items = mod.findings_for_text(art_texts[art], f"{n['id']} artifact {art}")
                hard += [it for it in items if not str(it).startswith("CLASSSEP-SOFT:")]
                soft += [it for it in items if str(it).startswith("CLASSSEP-SOFT:")]
    return hard, soft


hard_c, soft_c = map_hard(canon)
hard_s, soft_s = map_hard(shadow)
claim_c, claim_s = {}, {}
for i, c in enumerate(m.get("claims", [])):
    if not isinstance(c, dict):
        continue
    fc = [x for x in canon.findings(c, f"claims[{i}]", mode="prose")
          if not x.startswith("CLASSSEP-SOFT:")]
    fs = [x for x in shadow.findings(c, f"claims[{i}]", mode="prose")
          if not x.startswith("CLASSSEP-SOFT:")]
    if fc or fs:
        claim_c[i] = {"event_id": c.get("event_id"), "actor": c.get("actor"),
                      "findings": fc, "shadow_findings": fs}
map_battery = {
    "map_snapshot_sha256": sha256_bytes(map_bytes),
    "map_source_note": "live research_map/research_map.json snapshotted at run start; live hash at 00:49:26 was 6d3f0f2792a2",
    "artifact_texts_scanned": len(art_texts),
    "canonical_hard_count": len(hard_c),
    "shadow_hard_count": len(hard_s),
    "soft_counts": {"canonical": len(soft_c), "shadow": len(soft_s)},
    "claim_level": claim_c,
    "named_claim_ids_from_proposal": [
        {"index": i, "event_id": None}
    ],
    "canonical_hard": hard_c,
    "shadow_hard": hard_s,
}
(RAW / "map_battery.json").write_text(json.dumps(map_battery, indent=2, sort_keys=True))

# ---------------------------------------------------------------- growth experiment
GROWTH = [
    ("G1_meta_mention",
     "The audit flags our discussion of the C0/C2 merged label, but that is a metalinguistic mention, not a proposed merge."),
    ("G2_rejected_hypothesis",
     "We analysed the C0/C2 unified class only as a rejected hypothesis; the portfolio keeps the two classes split."),
    ("G3_counting_prose",
     "This note measures how often the C0/C2 combined pattern appears in review prose."),
]
growth_rows = []
for name, text in GROWTH:
    cc = [x for x in canon.findings({"statement": text}, f"growth:{name}", mode="prose")
          if not x.startswith("CLASSSEP-SOFT:")]
    ss = [x for x in shadow.findings({"statement": text}, f"growth:{name}", mode="prose")
          if not x.startswith("CLASSSEP-SOFT:")]
    growth_rows.append({"name": name, "text": text, "canonical": cc, "shadow": ss,
                        "canonical_delta": len(cc), "shadow_delta": len(ss)})
growth = {"probes": growth_rows,
          "canonical_delta_total": sum(r["canonical_delta"] for r in growth_rows),
          "shadow_delta_total": sum(r["shadow_delta"] for r in growth_rows),
          "shadow_le_canonical": sum(r["shadow_delta"] for r in growth_rows)
          <= sum(r["canonical_delta"] for r in growth_rows)}
(RAW / "growth.json").write_text(json.dumps(growth, indent=2, sort_keys=True))

# ---------------------------------------------------------------- acceptance evaluation
naive_named = {}
for i in (36, 94, 96, 97, 101, 112, 127, 144):
    if i < len(m.get("claims", [])) and isinstance(m["claims"][i], dict):
        c = m["claims"][i]
        fc = [x for x in canon.findings(c, f"claims[{i}]", mode="prose")
              if not x.startswith("CLASSSEP-SOFT:")]
        fs = [x for x in shadow.findings(c, f"claims[{i}]", mode="prose")
              if not x.startswith("CLASSSEP-SOFT:")]
        naive_named[i] = {"event_id": c.get("event_id"), "canonical": len(fc),
                          "shadow": len(fs), "shadow_zero": len(fs) == 0}
residual_named = {i: v for i, v in naive_named.items() if not v["shadow_zero"]}

acceptance = {
    "A1_shadow_corpus_no_fn": corpus_shadow["fn"] == 0,
    "A2_shadow_corpus_no_fp": corpus_shadow["fp"] == 0,
    "A3_declared_fp_probes_clean": all(r["ok"] for r in probes["fp"]),
    "A4_declared_tp_probes_fire": all(r["ok"] for r in probes["tp"]),
    "A5_named_claims_drop_to_zero": len(residual_named) == 0,
    "A6_declaration_parity": decl_parity_ok,
    "A7_growth_not_worse": growth["shadow_le_canonical"],
}
over_suppressed = [r["name"] for r in probes["fn"] if r["over_suppressed"]]

report = {
    "task_id": PRE["task_id"],
    "worker": PRE["worker"],
    "run_at": "2026-09-12T00:49:26+08:00",
    "valid": all(v["match"] for v in pin_report.values()),
    "pins": pin_report,
    "shadow_provenance": shadow_provenance,
    "corpus": {"canonical": {k: corpus_canon[k] for k in ("tp", "fn", "tn", "fp", "verdict")},
               "shadow": {k: corpus_shadow[k] for k in ("tp", "fn", "tn", "fp", "verdict")}},
    "probe_counts": {
        "fp_total": len(probes["fp"]), "fp_shadow_clean": sum(r["ok"] for r in probes["fp"]),
        "tp_total": len(probes["tp"]), "tp_shadow_fires": sum(r["ok"] for r in probes["tp"]),
        "adversarial_fn_probes": len(probes["fn"]), "over_suppressed": over_suppressed,
    },
    "map": {k: v for k, v in map_battery.items()
            if k not in ("canonical_hard", "shadow_hard", "claim_level")},
    "named_claims": naive_named,
    "residual_named_claims": residual_named,
    "growth": growth,
    "acceptance": acceptance,
    "acceptance_pass_count": sum(acceptance.values()),
    "acceptance_total": len(acceptance),
    "findings": [],
}
(RAW / "acceptance.json").write_text(json.dumps(acceptance, indent=2, sort_keys=True))

print(json.dumps({
    "valid": report["valid"],
    "shadow_only_insertions": shadow_provenance["only_insertions"],
    "corpus_canonical": report["corpus"]["canonical"],
    "corpus_shadow": report["corpus"]["shadow"],
    "probe_counts": report["probe_counts"],
    "map_hard": {"canonical": map_battery["canonical_hard_count"],
                 "shadow": map_battery["shadow_hard_count"]},
    "residual_named_claims": residual_named,
    "growth": {"canonical": growth["canonical_delta_total"], "shadow": growth["shadow_delta_total"]},
    "acceptance": acceptance,
}, indent=2, sort_keys=True))

(HERE / "report.json").write_text(json.dumps(report, indent=2, sort_keys=True))
manifest = {
    "task_id": PRE["task_id"],
    "generated_at": "2026-09-12T00:49:26+08:00",
    "pins": {k: v["sha256"] for k, v in PINS.items() if isinstance(v, dict) and "sha256" in v},
    "snapshot_map_sha256": sha256_bytes(map_bytes),
    "snapshot_canonical_sha256": sha256_bytes(canon_bytes),
    "shadow_sha256": sha256_bytes(shadow_text.encode()),
    "pre_registration_sha256": sha256_file(HERE / "pre_registration.json"),
}
(SNAP / "MANIFEST.json").write_text(json.dumps(manifest, indent=2, sort_keys=True))
print("wrote", HERE / "report.json")
