#!/usr/bin/env python3
"""W081-N0-C8-01: independent, hash-pinned review evidence for protocol C8.

Task (from map assignments astra-life02-n0-c8-refresh / astra-n0add-02):
re-issue the C8 verdict on numerics/CONVERGENCE_PROTOCOL.md at the hash measured
at review time, citing (i) scheme-appropriate invariant functional, (ii)
resolution-aware drift criterion, (iii) order fit with uncertainty, (iv)
negative controls.  A worker may not set a gate verdict; this script only
measures and writes evidence.

Machine checks performed (all reproducible from the repo root):
  A. moving-target guard: protocol sha256 at start and end of review
  B. every `path#hex` reference in the protocol and in the gate proposal's
     criteria resolves on disk to the cited prefix (or is classified)
  C. the four C8 criteria are present in the protocol text, with line numbers
  D. independent re-fit of numerics/tests/n0_order_4rung.json (>=4 rungs,
     monotone, band, R5 delta = max(pair half-range, LS SE), pairwise <= 0.25)
  E. numerics lock guard: script rc, numerics/spherical_solver absence,
     numerics_lock.state in research_map.json
  F. the gate proposal's quoted numbers vs the artifacts they come from
  G. C2 closure: protocol >= 4 rungs vs the A0 rubric requirement
"""
from __future__ import annotations

import hashlib
import json
import math
import re
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent
CST = timezone(timedelta(hours=8))
PROTOCOL = ROOT / "numerics" / "CONVERGENCE_PROTOCOL.md"
PROPOSAL = ROOT / "numerics" / "tests" / "n0_gate_proposal.json"
FOUR_RUNG = ROOT / "numerics" / "tests" / "n0_order_4rung.json"
FIXED_VERDICT = ROOT / "numerics" / "protocol" / "fixed_replication_verdict.json"
HASH_REGISTRY = ROOT / "runtime" / "state" / "artifact_hashes.json"
RUBRIC = ROOT / "evaluation_rubric.yaml"
MAP = ROOT / "research_map" / "research_map.json"
REF_RE = re.compile(r"([A-Za-z0-9_][A-Za-z0-9_./-]*)#([0-9a-f]{6,64})")


def now() -> str:
    return datetime.now(CST).isoformat(timespec="seconds")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def line_of(text: str, needle: str) -> int | None:
    for i, line in enumerate(text.splitlines(), 1):
        if needle in line:
            return i
    return None


def ls_fit(xs, ys):
    """Least-squares slope/intercept of y vs x plus slope standard error."""
    n = len(xs)
    mx = sum(xs) / n
    my = sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    slope = sxy / sxx
    intercept = my - slope * mx
    resid = [y - (intercept + slope * x) for x, y in zip(xs, ys)]
    dof = n - 2
    s2 = sum(r * r for r in resid) / dof if dof > 0 else float("nan")
    se = math.sqrt(s2 / sxx) if dof > 0 else float("nan")
    return slope, intercept, se


result: dict = {
    "schema": "w081-evidence-check/n0-c8/v1",
    "task_id": "W081-N0-C8-01",
    "actor": "worker-081",
    "created_at": now(),
    "class_id": "AF-WCC-SCALAR-SPH",
    "node_id": "N0",
    "gate": "G-NUM",
    "authority_note": "Worker evidence only: no status=done, validation_status=passed, or gate verdict is set here.",
    "checks": {},
    "findings": [],
}

# ---------------------------------------------------------------- A: moving target
proto_hash_start = sha256(PROTOCOL)
result["checks"]["A_moving_target"] = {
    "protocol": "numerics/CONVERGENCE_PROTOCOL.md",
    "sha256_at_start": proto_hash_start,
    "review_started_at": now(),
}

# ---------------------------------------------------------------- B: hash references
# A reference is binding unless it is explicitly historical (supersedes / prior
# revision) or points at a mutable live registry (artifact_hashes.json is
# regenerated by every checkpoint).  Only unacknowledged binding mismatches block.
MUTABLE_REGISTRIES = {"artifact_hashes.json", "current_checkpoint.json", "events.jsonl",
                      "ingested_ids.json", "checkpoint_log.jsonl"}


def json_key_paths(obj, prefix, path=()):
    """All key paths whose JSON value contains the literal prefix string."""
    out = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            out += json_key_paths(v, prefix, path + (str(k),))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            out += json_key_paths(v, prefix, path + (f"[{i}]",))
    elif isinstance(obj, str) and prefix in obj:
        out.append(".".join(path))
    return out


def classify_ref(source_name, target, prefix, protocol_text):
    entry = {"source": source_name, "target": target, "prefix": prefix}
    p = ROOT / target
    if not p.exists():
        entry.update(status="MISSING", measured_sha256=None, binding=True)
        return entry
    measured = sha256(p)
    entry["measured_sha256"] = measured
    entry["status"] = "MATCH" if measured.startswith(prefix) else "MISMATCH"
    path = Path(target).name
    if source_name == "gate_proposal":
        ctx = json_key_paths(json.loads(read_text(PROPOSAL)), prefix)
    else:
        ctx = [ln for ln in protocol_text.splitlines() if prefix in ln]
    entry["context"] = ctx[:4]
    if entry["status"] == "MATCH":
        entry["binding"] = True
        entry["disposition"] = "binding-pin-verified"
        return entry
    if path in MUTABLE_REGISTRIES:
        entry.update(binding=False, disposition="snapshot-pin-of-mutable-registry")
        return entry
    if any("supersede" in c.lower() for c in ctx):
        entry.update(binding=False, disposition="supersedes-pointer-historical")
        return entry
    if target.startswith("reviews/"):
        preserved = None
        for cand in sorted((ROOT / "reviews").glob("*.json")):
            if sha256(cand).startswith(prefix):
                preserved = str(cand.relative_to(ROOT))
                break
        if preserved:
            entry.update(binding=False, disposition=f"superseded-review-record-predecessor-preserved-at:{preserved}")
            return entry
        entry.update(binding=True, disposition="unacknowledged-review-record-mismatch")
        return entry
    if source_name == "protocol" and any(
            ("superseded" in ln or "provisional" in ln) for ln in protocol_text.splitlines()
            if prefix[:8] in ln or "formulation_taxonomy" in ln):
        entry.update(binding=False, disposition="protocol-declares-pin-provisional-or-superseded")
        return entry
    entry.update(binding=True, disposition="unacknowledged-binding-mismatch")
    return entry


refs = []
for source_name, path in (("protocol", PROTOCOL), ("gate_proposal", PROPOSAL)):
    text = read_text(path)
    for m in REF_RE.finditer(text):
        target, prefix = m.group(1), m.group(2)
        if "/" in target and target.split("/")[0] in {
            "numerics", "runtime", "artifacts", "reviews", "schemas", "ledger",
            "research_map", "comms", "evaluation", "data",
        }:
            refs.append((source_name, target, prefix))

ref_checks = []
seen = set()
for source_name, target, prefix in refs:
    key = (source_name, target, prefix)
    if key in seen:
        continue
    seen.add(key)
    ref_checks.append(classify_ref(source_name, target, prefix, read_text(PROTOCOL) if source_name == "protocol" else ""))

binding_bad = [e for e in ref_checks if e["status"] != "MATCH" and e["binding"]]
result["checks"]["B_hash_refs"] = {
    "total": len(ref_checks),
    "match": sum(1 for e in ref_checks if e["status"] == "MATCH"),
    "mismatch": sum(1 for e in ref_checks if e["status"] == "MISMATCH"),
    "missing": sum(1 for e in ref_checks if e["status"] == "MISSING"),
    "binding_mismatch": len(binding_bad),
    "non_binding_mismatch": sum(1 for e in ref_checks if e["status"] != "MATCH" and not e["binding"]),
    "entries": ref_checks,
}

# ---------------------------------------------------------------- C: four criteria
proto_text = read_text(PROTOCOL)
proto_lines = proto_text.splitlines()
criteria = {
    "i_scheme_appropriate_invariant_functional": {
        "markers": ["R1 — declare the functional", "R2 — exact discrete conservation", "R4 — no cross-scheme functional gate"],
        "lines": {m: line_of(proto_text, m) for m in
                  ["R1 — declare the functional", "R2 — exact discrete conservation", "R4 — no cross-scheme functional gate"]},
        "note": "§4.1 R1/R2/R4; R4 explicitly demotes the harness functional to a labelled mismatch diagnostic",
    },
    "ii_resolution_aware_drift_criterion": {
        "markers": ["R3 — convergent diagnostics", "decrease at order", "not admissible"],
        "lines": {m: line_of(proto_text, m) for m in
                  ["R3 — convergent diagnostics", "decrease at order", "not admissible"]},
        "note": "§4.1 R3: drift must decrease at order >= p_decl - 0.5 across >= 3 rungs, finest <= 1e-6",
    },
    "iii_order_fit_with_uncertainty": {
        "markers": ["R5", "R5a", "least-squares standard error"],
        "lines": {m: line_of(proto_text, m) for m in
                  ["R5", "R5a", "least-squares standard error"]},
        "note": "§3.8: p ± delta, delta = max(pair-spread half-range, LS SE); R5a names the norm",
    },
    "iv_negative_controls": {
        "markers": ["Negative controls (must fail)", "frozen-in-time solver", "sign-flipped Laplacian",
                    "CFL violation", "naive collocated scheme"],
        "lines": {m: line_of(proto_text, m) for m in
                  ["Negative controls (must fail)", "frozen-in-time solver", "sign-flipped Laplacian",
                   "CFL violation", "naive collocated scheme"]},
        "note": "§5: four controls that must be rejected; a calibration accepting any control is invalid",
    },
}
criteria_present = {k: all(v is not None for v in c["lines"].values()) for k, c in criteria.items()}
result["checks"]["C_criteria_present"] = {
    "per_criterion": criteria_present,
    "all_present": all(criteria_present.values()),
    "detail": criteria,
}

# ---------------------------------------------------------------- D: independent re-fit
four = json.loads(read_text(FOUR_RUNG))
studies = four.get("studies", [])
refit = []
all_ok = True
for s in studies:
    rows = s.get("rows", [])
    hs = [r["dr"] for r in rows]
    es = [r["l2_error"] for r in rows]
    n = len(rows)
    xs = [math.log(h) for h in hs]
    ys = [math.log(e) for e in es]
    slope, intercept, se = ls_fit(xs, ys)
    pair_orders = [math.log(es[i] / es[i + 1]) / math.log(hs[i] / hs[i + 1]) for i in range(n - 1)]
    half_range = (max(pair_orders) - min(pair_orders)) / 2 if pair_orders else float("nan")
    delta = max(half_range, se)
    monotone = all(es[i] > es[i + 1] for i in range(n - 1))
    band = abs(slope - four["config"]["p_expected"]) <= four["config"]["p_tol"]
    entry = {
        "scheme": s.get("scheme"),
        "rungs": n,
        ">=4_rungs": n >= 4,
        "monotone": monotone,
        "within_band": band,
        "reported_fit_order": s.get("fit_order"),
        "recomputed_fit_order": slope,
        "fit_order_abs_diff": abs(slope - s.get("fit_order", float("nan"))),
        "reported_delta": s.get("delta"),
        "recomputed_delta": delta,
        "delta_abs_diff": abs(delta - s.get("delta", float("nan"))),
        "reported_least_squares_se": s.get("least_squares_se"),
        "recomputed_least_squares_se": se,
    }
    entry["ok"] = (entry[">=4_rungs"] and monotone and band
                   and entry["fit_order_abs_diff"] < 1e-9 and entry["delta_abs_diff"] < 1e-9)
    all_ok = all_ok and entry["ok"]
    refit.append(entry)
pair_diffs = []
for i in range(len(studies)):
    for j in range(i + 1, len(studies)):
        pair_diffs.append(abs(studies[i]["fit_order"] - studies[j]["fit_order"]))
result["checks"]["D_four_rung_refit"] = {
    "studies": refit,
    "all_studies_ok": all_ok,
    "max_pairwise_order_diff": max(pair_diffs) if pair_diffs else None,
    "r5_floor": 0.25,
    "pairwise_ok": (max(pair_diffs) <= 0.25) if pair_diffs else False,
}

# ---------------------------------------------------------------- E: lock guard
guard = ROOT / "numerics" / "tests" / "selfgravity_lock_guard.py"
guard_run = {"script": "numerics/tests/selfgravity_lock_guard.py", "sha256": sha256(guard) if guard.exists() else None}
try:
    cp = subprocess.run([sys.executable, str(guard)], cwd=str(ROOT), capture_output=True,
                        text=True, timeout=180)
    guard_run["returncode"] = cp.returncode
    guard_run["stdout_tail"] = cp.stdout.strip().splitlines()[-6:]
    guard_run["stderr_tail"] = cp.stderr.strip().splitlines()[-4:]
    guard_run["stdout_sha256"] = hashlib.sha256(cp.stdout.encode()).hexdigest()
except Exception as exc:  # pragma: no cover
    guard_run["returncode"] = None
    guard_run["error"] = repr(exc)
lock = json.loads(read_text(MAP)).get("numerics_lock", {})
result["checks"]["E_lock"] = {
    "guard": guard_run,
    "guard_passed": guard_run.get("returncode") == 0,
    "spherical_solver_exists": (ROOT / "numerics" / "spherical_solver").exists(),
    "numerics_lock_state": lock.get("state"),
    "numerics_lock_ok": lock.get("state") == "locked",
}

# ---------------------------------------------------------------- F: proposal numbers
proposal = json.loads(read_text(PROPOSAL))
fixed = json.loads(read_text(FIXED_VERDICT))
claim = proposal["certified_order_claim"]
reported_max_4 = 0.0
for s in studies:
    reported_max_4 = max(reported_max_4, s.get("fit_order", 0.0))
reported_4_max_pair = max(pair_diffs) if pair_diffs else None
proposal_claim_text = json.dumps(claim)
num_ok = {
    "max_pairwise_4rung_claimed_0.007765": abs((reported_4_max_pair or 0.0) - 0.007765) < 5e-6,
    "four_rung_all_within_band": proposal["fourth_resolution"]["all_within_band"],
    "all_schemes_4_rungs": proposal["fourth_resolution"]["all_schemes_4_rungs"],
    "c8_status": [c for c in proposal["criteria"] if c["id"] == "protocol-reviewed-by-audit"][0]["status"],
    "c5_status": [c for c in proposal["criteria"] if c["id"] == "registration-in-artifact-hashes"][0]["status"],
}
registry_text = read_text(HASH_REGISTRY)
num_ok["fixed_run_registered"] = "6542db93eebc5095" in registry_text
num_ok["four_rung_registered"] = "c88146a1375c50f0" in registry_text
num_ok["protocol_rev3_registered"] = "1e6cdf04d7a2" in registry_text
result["checks"]["F_proposal_numbers"] = {
    "reported_max_pairwise_order_diff_4rung": reported_4_max_pair,
    "fixed_verdict_keys": sorted(fixed.keys())[:25],
    "checks": num_ok,
}

# ---------------------------------------------------------------- G: C2 closure
rubric_text = read_text(RUBRIC) if RUBRIC.exists() else ""
protocol_says_four = "at least four resolutions for an order-certification claim" in proto_text.lower()
rubric_four = bool(re.search(r"(>=|at least|≥)\s*4\s*(resolutions|rungs)", rubric_text, re.I)) or "4 resolutions" in rubric_text
result["checks"]["G_c2_closure"] = {
    "protocol_requires_4_rungs": protocol_says_four,
    "protocol_4rung_evidence_present": FOUR_RUNG.exists(),
    "rubric_mentions_4": rubric_four,
    "rev3_log_closes_c2": "C2" in proto_text and "Revision 3 amendment" in proto_text,
}

# ---------------------------------------------------------------- H: concurrent audit verdict
lead_review = ROOT / "reviews" / "G-NUM-protocol-review.json"
concurrent = {"path": "reviews/G-NUM-protocol-review.json", "exists": lead_review.exists()}
if lead_review.exists():
    lr = json.loads(read_text(lead_review))
    concurrent.update({
        "sha256": sha256(lead_review),
        "verdict": lr.get("verdict"),
        "reviewer": lr.get("reviewer"),
        "reviewed_sha256": lr.get("reviewed_sha256"),
        "supersedes_sha256": lr.get("supersedes_sha256"),
        "created_at": lr.get("created_at"),
        "binds_same_protocol_hash": lr.get("reviewed_sha256") == proto_hash_start,
    })
result["checks"]["H_concurrent_audit_verdict"] = concurrent

# ---------------------------------------------------------------- findings
findings = []
for e in ref_checks:
    if e["status"] != "MATCH":
        findings.append({
            "id": f"W081-F-REF-{e['target'].split('/')[-1]}-{e['prefix'][:8]}",
            "severity": "blocking" if e["binding"] else "non-blocking",
            "statement": f"{e['source']} reference {e['target']}#{e['prefix']} is {e['status']} on disk"
                         + (f" (measured {e['measured_sha256'][:16]})" if e["measured_sha256"] else ""),
            "disposition": e["disposition"],
            "context": e.get("context", []),
        })
if not result["checks"]["C_criteria_present"]["all_present"]:
    findings.append({"id": "W081-F-CRIT-MISSING", "severity": "blocking",
                     "statement": "one or more C8 criteria markers absent from the protocol text"})
if not result["checks"]["D_four_rung_refit"]["all_studies_ok"]:
    findings.append({"id": "W081-F-4RUNG", "severity": "blocking",
                     "statement": "independent re-fit disagrees with the reported 4-rung orders/uncertainties"})
if not result["checks"]["D_four_rung_refit"]["pairwise_ok"]:
    findings.append({"id": "W081-F-R5", "severity": "blocking",
                     "statement": "pairwise scheme disagreement exceeds the R5 floor"})
if not result["checks"]["E_lock"]["guard_passed"] or not result["checks"]["E_lock"]["numerics_lock_ok"]:
    findings.append({"id": "W081-F-LOCK", "severity": "blocking", "statement": "lock guard failed or lock not locked"})
if not num_ok["fixed_run_registered"] or not num_ok["protocol_rev3_registered"]:
    findings.append({
        "id": "W081-F-REG",
        "severity": "non-blocking",
        "statement": "COMMS PROTOCOL rule 2 registration gap: the FIXED replication run (6542db93) and/or the "
                     "rev-3 protocol hash (1e6cdf04d7a2) are not in runtime/state/artifact_hashes.json; this is the "
                     "proposal's own C5 (controller-owned) and does not bear on the protocol's content.",
    })
if num_ok["c8_status"] != "unmet":
    findings.append({"id": "W081-F-C8STATE", "severity": "non-blocking",
                     "statement": f"proposal records C8 status={num_ok['c8_status']!r}; this review supplies evidence for a C8 verdict at the measured hash"})
findings.append({
    "id": "W081-F-F0PIN",
    "severity": "non-blocking",
    "statement": "the protocol's opening F0 pin (research_map/formulation_taxonomy.yaml#66bf917bd368) no longer "
                 "matches the canonical file as measured at review time (see W081-F-REF-formulation_taxonomy.yaml-66bf917b); "
                 "the protocol itself declares the pin superseded and class_binding provisional, and the order claim "
                 "does not depend on it. Re-pin on the next revision.",
})
result["findings"] = findings
hard = [f for f in findings if f["severity"] == "blocking"]
result["verdict_inputs"] = {
    "blocking_findings": len(hard),
    "criteria_satisfied": result["checks"]["C_criteria_present"]["all_present"],
    "evidence_hash_refs_match": result["checks"]["B_hash_refs"]["binding_mismatch"] == 0,
    "four_rung_refit_ok": all_ok,
    "lock_ok": result["checks"]["E_lock"]["guard_passed"] and result["checks"]["E_lock"]["numerics_lock_ok"],
}

# ---------------------------------------------------------------- A (end) + write
proto_hash_end = sha256(PROTOCOL)
result["checks"]["A_moving_target"].update({
    "sha256_at_end": proto_hash_end,
    "stable": proto_hash_start == proto_hash_end,
    "review_finished_at": now(),
})
if proto_hash_start != proto_hash_end:
    result["findings"].append({"id": "W081-F-MOVING", "severity": "blocking",
                               "statement": "protocol changed during review; verdict must not bind a stale hash"})
    result["verdict_inputs"]["blocking_findings"] += 1
result["reviewed_sha256"] = proto_hash_start

(OUT / "evidence_check.json").write_text(json.dumps(result, indent=1, sort_keys=True) + "\n")

verdict = "accept" if result["verdict_inputs"]["blocking_findings"] == 0 else "revise"
review = {
    "schema": "w081-review/g-num-protocol/v1",
    "event_id": "w081-n0-c8-review-20260912T0019",
    "event_type": "review",
    "created_at": now(),
    "actor": "worker-081",
    "target_id": "G-NUM-protocol",
    "node_id": "N0",
    "gate": "G-NUM",
    "class_id": "AF-WCC-SCALAR-SPH",
    "reviewer": "worker-081",
    "reviewer_independence": "bounded execution worker; author of no N0 solver, protocol, rubric, or gate artifact; "
                             "all reviewed bytes hashed by this worker at review time",
    "verdict": verdict,
    "score": 4.0 if verdict == "accept" else 3.0,
    "hard_failures": [f["statement"] for f in hard],
    "findings": findings,
    "artifact_sha256": proto_hash_start,
    "reviewed_artifacts": {
        "numerics/CONVERGENCE_PROTOCOL.md": proto_hash_start,
        "numerics/tests/n0_gate_proposal.json": sha256(PROPOSAL),
        "numerics/tests/n0_order_4rung.json": sha256(FOUR_RUNG),
        "numerics/protocol/fixed_replication_verdict.json": sha256(FIXED_VERDICT),
        "artifacts/worker-081/n0_c8_protocol_review/evidence_check.json": None,
    },
    "criteria_verdicts": {
        "i_scheme_appropriate_invariant_functional": "accept" if criteria_present["i_scheme_appropriate_invariant_functional"] else "revise",
        "ii_resolution_aware_drift_criterion": "accept" if criteria_present["ii_resolution_aware_drift_criterion"] else "revise",
        "iii_order_fit_with_uncertainty": "accept" if criteria_present["iii_order_fit_with_uncertainty"] and all_ok else "revise",
        "iv_negative_controls": "accept" if criteria_present["iv_negative_controls"] else "revise",
    },
    "falsifier": "Re-measure numerics/CONVERGENCE_PROTOCOL.md: if its sha256 is not "
                 f"{proto_hash_start[:16]}, this verdict does not bind. It is also falsified if any cited evidence "
                 "path#hash reference re-hashes differently, if the 4-rung study loses a rung or leaves p=2.0+-0.3, "
                 "or if selfgravity_lock_guard.py exits non-zero / numerics/spherical_solver appears.",
}
if proto_hash_end != proto_hash_start:
    review["verdict"] = "inconclusive"
    review["hard_failures"].append("protocol hash moved during review: moving target, no binding verdict")
review["reviewed_artifacts"]["artifacts/worker-081/n0_c8_protocol_review/evidence_check.json"] = sha256(
    OUT / "evidence_check.json")
(OUT / "review.json").write_text(json.dumps(review, indent=1, sort_keys=True) + "\n")
print(json.dumps({
    "verdict": review["verdict"],
    "reviewed_sha256": proto_hash_start[:16],
    "stable": proto_hash_end == proto_hash_start,
    "refs": {k: result["checks"]["B_hash_refs"][k] for k in ("total", "match", "mismatch", "missing")},
    "criteria": criteria_present,
    "four_rung_ok": all_ok,
    "max_pairwise": result["checks"]["D_four_rung_refit"]["max_pairwise_order_diff"],
    "lock_ok": result["checks"]["E_lock"]["guard_passed"] and result["checks"]["E_lock"]["numerics_lock_ok"],
    "findings": [(f["id"], f["severity"]) for f in findings],
}, indent=1))
