#!/usr/bin/env bash
set -u
ROOT=/data3/guoshaoyang/workdir/ai4math-swarm
B=$ROOT/runtime; I=$B/instances; C=$B/control; S=$B/state
mkdir -p "$I" "$C" "$S"
launch(){ role=$1; slot=$2; prompt=$3; key="\${role}-\${slot}"; tmux has-session -t "$key" 2>/dev/null && return; stamp=$(date +%Y%m%dT%H%M%S); id="\${key}-\${stamp}-$$"; d="\${I}/\${id}"; mkdir -p "$d"; printf '%s\n' "$prompt" > "$d/prompt.txt"; printf '{"id":"%s","role":"%s","slot":"%s","started_at":"%s"}\n' "$id" "$role" "$slot" "$(date -Is)" > "$d/meta.json"; tmux new-session -d -s "$key" "echo start id=$id ts=$(date -Is) >> '$d/trajectory.log'; '$HOME/workdir/lean_poincare/bin/dsh_fixed.sh' --profile headless '$prompt' > '$d/stdout.log' 2> '$d/stderr.log'; rc=\$?; echo \$rc > '$d/exit_code'; echo exit id=$id rc=\$rc ts=$(date -Is) >> '$d/trajectory.log'"; echo "$(date -Is) launch $key $id" >> "$S/supervisor.log"; }
controller='You are Astra controller. Read ASTRA_HANDOFF.md and research_map.json. Consume comms and artifacts, maintain DAG and gates, issue bounded assignments, record hashes validation ETA. Keep numerics gated. One independent lifecycle then exit.'
lead='You are a group lead. Read handoff/map and comms. Review artifacts, consume queue, emit structured events and checkpoints, report blockers. One independent lifecycle then exit.'
worker='You are a bounded execution worker. Read handoff/map and comms. Take one class-bound task, emit valid JSON event with IDs evidence hash falsifier, checkpoint, then exit.'
while :; do launch controller 01 "$controller"; for g in formulation literature numerics audit; do launch lead-$g 01 "$lead group=$g"; done; for n in $(seq -w 1 20); do launch worker "$n" "$worker worker=$n"; done; echo "$(date -Is) sessions=$(tmux ls 2>/dev/null | egrep "^(controller|lead-|worker-)" | wc -l) leads=$(tmux ls 2>/dev/null | grep -c "^lead-") workers=$(tmux ls 2>/dev/null | grep -c "^worker-") artifacts=$(find "$ROOT/artifacts" -type f 2>/dev/null | wc -l)" >> "$S/counts.tsv"; sleep 20; done
