#!/usr/bin/env python3
"""Emit worker-07 outbox events (validated against research_map/schemas.py).

Upward messages:
  L0  status   + artifact  -> ledger/theorems.jsonl contribution (assigned task)
  L1  artifact             -> quote-grounding checker + coverage finding
  A1  artifact + claim + resource_request -> class-separation falsification harness
      (produced under the no-assignment branch at 23:16-23:20, before the 23:19 card
       was found; emitted separately and clearly labelled)
"""
from __future__ import annotations

import hashlib
import json
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "research_map"))
from schemas import validate_event  # noqa: E402

OUT = ROOT / "comms" / "outbox" / "deepseek-flash-07"
CST = timezone(timedelta(hours=8))
NOW = datetime.now(CST).isoformat(timespec="seconds")
ACTOR = "deepseek-flash-07"
LEDGER = ROOT / "ledger" / "theorems.jsonl"
SRC_B = ROOT / "artifacts" / "literature" / "sources" / "batch-w07.jsonl"
THM_B = ROOT / "artifacts" / "literature" / "theorems" / "batch-w07.jsonl"
L0_REPORT = ROOT / "artifacts" / "worker-07" / "ledger_contribution" / "REPORT.md"
GROUND = ROOT / "artifacts" / "worker-07" / "ledger_contribution" / "grounding_report.json"
HARNESS = ROOT / "artifacts" / "worker-07" / "class_separation_falsification" / "results.json"
HARNESS_RPT = ROOT / "artifacts" / "worker-07" / "class_separation_falsification" / "REPORT.md"
SNAP = (ROOT / "artifacts" / "worker-07" / "class_separation_falsification"
        / "target_snapshots" / "audit_evidence.c4769b99ab70.py")


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def rel(p: Path) -> str:
    return str(p.relative_to(ROOT))


CLASSES = ["AF-WCC-VAC-GEN", "AF-SCC-C2-VAC-GEN", "AF-SCC-C0-VAC-GEN", "AF-WCC-SCALAR-SPH"]

EVENTS = [
    {
        "event_id": "w07-status-L0-20260911T2335",
        "event_type": "status",
        "created_at": NOW,
        "actor": ACTOR,
        "node_id": "L0",
        "status": "active",
        "hours": 0.6,
        "summary": (
            "Worker-07 accepted assignment asg-2026-09-11-L0-deepseek-flash-07-16 (card read 23:26; "
            "inbox was empty at 23:16-23:20). Delivered L0 contribution without touching other agents' "
            "batches: 7 source records (5 verified by arXiv abstract fetch with page+quote, 2 honestly "
            "unresolved) and 15 theorem rows (9 accepted, 4 provisional, 2 unresolved) in new files "
            "artifacts/literature/{sources,theorems}/batch-w07.jsonl; ran the literature lead's builder, "
            "ledger/theorems.jsonl now has 37 rows (15 mine, 22 lead's). All 15 rows carry explicit "
            "non-claims; no node status=done, no validation_status=passed, no gate verdict claimed. "
            "Secondary: a falsification harness for audit_evidence.py's class-separation check was "
            "completed at 23:20 under the no-assignment branch (separate events)."
        ),
        "evidence_refs": [
            f"ledger/theorems.jsonl#{sha(LEDGER)[:8]}",
            f"artifacts/literature/sources/batch-w07.jsonl#{sha(SRC_B)[:8]}",
            f"artifacts/literature/theorems/batch-w07.jsonl#{sha(THM_B)[:8]}",
            f"artifacts/worker-07/ledger_contribution/REPORT.md#{sha(L0_REPORT)[:8]}",
        ],
        "next_falsifier": (
            "An L1 re-fetch resolves one of W07-SRC-01..05 to a different work than its row claims, or "
            "the Christodoulou 1999 full text contradicts the scope-only row W07-TH-11."
        ),
    },
    {
        "event_id": "w07-artifact-L0-ledger-20260911T2335",
        "event_type": "artifact",
        "created_at": NOW,
        "actor": ACTOR,
        "node_id": "L0",
        "artifact_type": "theorem_ledger_contribution",
        "path": rel(LEDGER),
        "sha256": sha(LEDGER),
        "validation_status": "unverified",
        "authored_rows": 15,
        "rows_total_at_build": 37,
        "contribution_batches": [rel(SRC_B), rel(THM_B)],
        "generator": "artifacts/worker-07/ledger_contribution/build_w07_batches.py",
        "class_ids": CLASSES + ["DEFINITIONS", "AF-WCC-VAC-BH-FORM", "AF-WCC-VAC-NS-CONSTR",
                                "AF-SCC-OTHER-MODELS"],
        "note": ("Ledger is generated by artifacts/literature/tools/build_literature.py from batch-*.jsonl; "
                 "any rebuild that includes batch-w07.jsonl reproduces these rows. Hash is build-time and "
                 "will change when other batches are added."),
    },
    {
        "event_id": "w07-artifact-L1-grounding-20260911T2335",
        "event_type": "artifact",
        "created_at": NOW,
        "actor": ACTOR,
        "node_id": "L1",
        "artifact_type": "verification_tool_and_report",
        "path": rel(GROUND),
        "sha256": sha(GROUND),
        "validation_status": "unverified",
        "tool": "artifacts/worker-07/ledger_contribution/check_grounding.py",
        "finding": ("16 of 25 accepted ledger rows declare no grounding entries; all 16 are the literature "
                    "lead's rows, none are worker-07's. This is a checkability gap, not proof of citation "
                    "error: their support may be quoted inside statement_exact, which the checker does not "
                    "parse. All 30 declared quotes in worker-07's 13 grounded rows match their sources."),
        "next_falsifier": ("L1 accepts ungrounded rows (finding is a gap, not a defect) or rejects them "
                           "(16 rows fail the stricter check); either outcome is recorded, not hidden."),
    },
    {
        "event_id": "w07-artifact-A1-classsep-20260911T2335",
        "event_type": "artifact",
        "created_at": NOW,
        "actor": ACTOR,
        "node_id": "A1",
        "artifact_type": "falsification_harness",
        "path": rel(HARNESS),
        "sha256": sha(HARNESS),
        "validation_status": "unverified",
        "report": rel(HARNESS_RPT),
        "report_sha256": sha(HARNESS_RPT),
        "target": "research_map/audit_evidence.py::audit",
        "target_revision_snapshot": rel(SNAP),
        "target_revision_sha256": sha(SNAP),
        "target_live_sha256_now": sha(ROOT / "research_map" / "audit_evidence.py"),
        "class_ids": CLASSES,
        "verdict": ("At revision c4769b99ab70: 3/17 class-merge fixtures detected, 14 missed, 1/10 "
                    "legitimate controls falsely flagged; the gate is defective on that revision."),
    },
    {
        "event_id": "w07-claim-A1-classsep-20260911T2335",
        "event_type": "claim",
        "created_at": NOW,
        "actor": ACTOR,
        "class_id": "AF-SCC-C2-VAC-GEN",
        "statement": (
            "Counterexample to the sufficiency of the class-separation check in "
            "research_map/audit_evidence.py at revision c4769b99ab70: a map node whose label is "
            "'AF-SCC C0/C2 schema' - a single document covering both AF-SCC-C0-VAC-GEN and "
            "AF-SCC-C2-VAC-GEN - produces zero hard failures (fixture L02_slash of the harness). "
            "13 further genuine class-hygiene violations also escape, including WCC/SCC unification, "
            "an SCC conclusion on a WCC class, and merges in unscanned fields (direction, "
            "portfolio_events, notes); conversely fixture C08 ('keep C0 and C2 separate') is falsely "
            "flagged. Applies to the frozen snapshot only."
        ),
        "conclusion_type": "counterexample",
        "assumptions": [
            "target pinned at sha256 c4769b99ab706146c4091fbe51d3e4dcd4faa8ded0c77f12342c74df6d9064a5 (snapshot preserved)",
            "minimal single-node synthetic maps with status=queued isolate the class-separation logic",
            "is_class_merge ground truth is worker-07's reading of ASTRA hard decision 1 and A1's "
            "'reject class leakage and conclusion inflation' mandate; it requires lead adjudication",
        ],
        "falsifier": (
            "lead-formulation adjudicates L02/C08-style fixtures as legitimate documents, or a revised "
            "gate rejects all 17 leak fixtures while accepting all 10 controls - either falsifies this claim."
        ),
        "evidence_refs": [
            f"artifacts/worker-07/class_separation_falsification/results.json#{sha(HARNESS)[:8]}",
            f"artifacts/worker-07/class_separation_falsification/REPORT.md#{sha(HARNESS_RPT)[:8]}",
            f"artifacts/worker-07/class_separation_falsification/target_snapshots/audit_evidence.c4769b99ab70.py#{sha(SNAP)[:8]}",
        ],
        "artifact_refs": [rel(HARNESS), rel(HARNESS_RPT)],
        "scope": "swarm-infrastructure/verification-layer; not a physics claim",
    },
    {
        "event_id": "w07-resource-A1-classsep-20260911T2335",
        "event_type": "resource_request",
        "created_at": NOW,
        "actor": ACTOR,
        "group_id": "audit",
        "requested_agents": 1,
        "requested_agent_hours": 1.5,
        "justification": (
            "Independent reviewer (A1) to adjudicate the 17 leak fixtures blind to the checker, starting "
            "with L02 and C08, and to confirm or refute the counterexample claim w07-claim-A1-classsep. "
            "This converts worker-07's domain ground truth into accepted findings and turns the harness "
            "into a regression gate for the fixed checker."
        ),
        "expected_information_gain": (
            "Either a confirmed soundness defect in the shared evidence gate (blocking A1/G-AUDIT) or a "
            "falsified ground-truth label (which corrects worker-07); both outcomes reduce review risk."
        ),
        "stop_rule": (
            "Stop after one adjudicated pass over the fixture corpus, or 1.5 agent-hours, whichever is "
            "first; unresolved fixtures stay unresolved."
        ),
    },
]


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for e in EVENTS:
        validate_event(e)                       # fail before writing anything invalid
    for e in EVENTS:
        p = OUT / f"{e['event_id']}.json"
        p.write_text(json.dumps(e, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
        print(f"wrote {p.relative_to(ROOT)}")
    print(f"{len(EVENTS)} events validated against research_map/schemas.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
