#!/usr/bin/env python3
"""W020-N0-FIXEDDT-VERIFY-01 — independent verification of the lead's fixed-dt N0 control.

TARGET (read-only, hash-pinned)
  numerics/protocol/temporal_subdominance_control.json
  generated by numerics/protocol/temporal_subdominance_control.py (astra-lead-numerics)

WHAT IS VERIFIED
  A. Recomputation: every derived statistic filed in the target (fit_order, pair_orders,
     pair_half_range, least_squares_se, delta_R5, monotone, within_band, rule_a, p_cfl) is
     recomputed from the target's own raw rows by this script's own arithmetic.
  B. Fresh re-run: the fixed-dt ladders B (dt = 1e-3 and 5e-4, dr = 0.2/0.1/0.05/0.025,
     lffd/cnfd/cnfem) and the temporal sweeps C are re-executed in a fresh process against the
     frozen module numerics/tests/flat_wave_replication.py at its pinned sha256.  Determinism
     is checked by re-running selected points.
  C. Rule audit: the pre-registered admissibility rules are re-evaluated as written and as
     implemented; the one-sided rule_b is re-checked symmetrically.

AUTHORITY / LIMITS
  Worker evidence only: no gate verdict, no node completion, no edit to any canonical path.
  The frozen module is imported read-only under a hash guard; nothing is written outside
  artifacts/worker-020/n0_fixed_dt_control_verify/.

FALSIFIER
  This verification is void if the target or frozen module re-hashes differently, or if a
  fresh re-run at the pinned frozen-module hash reproduces the filed fixed-dt row errors only
  outside 1e-9 relative, or if the filed B ladders are outside |p - 2| <= 0.3.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import platform
import sys
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]

TARGET = REPO / "numerics" / "protocol" / "temporal_subdominance_control.json"
GENERATOR = REPO / "numerics" / "protocol" / "temporal_subdominance_control.py"
FROZEN = REPO / "numerics" / "tests" / "flat_wave_replication.py"
R_MAX = 30.0
T_END = 6.0
DR_VALUES = [0.2, 0.1, 0.05, 0.025]
P_EXPECTED = 2.0
P_TOL = 0.3
R5_FLOOR = 0.25
REL_TOL = 1e-9

PINNED = {
    "numerics/protocol/temporal_subdominance_control.json":
        "334f5b71e0d53ab6ed1f3b7133abca541a36dafc9a5cfb4f62f0655839dd964b",
    "numerics/tests/flat_wave_replication.py":
        "8ade1cdc163ea420790b9fdfdab41157b4f3d4219d6a0bcf827baafe69a6f422",
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_frozen(expected: str):
    got = sha256(FROZEN)
    if got != expected:
        raise SystemExit(f"FROZEN HASH MISMATCH: {got} != {expected}")
    spec = importlib.util.spec_from_file_location("frozen_n0_replication", FROZEN)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod, got


def ols(drs, errs):
    x = np.log(np.asarray(drs, float))
    y = np.log(np.asarray(errs, float))
    slope, intercept = np.polyfit(x, y, 1)
    pred = slope * x + intercept
    resid = y - pred
    rss = float(np.sum(resid * resid))
    sxx = float(np.sum((x - x.mean()) ** 2))
    se = math.sqrt(rss / (len(x) - 2) / sxx) if len(x) > 2 else float("nan")
    return float(slope), [float(r) for r in resid], float(se)


def pair_orders(drs, errs):
    return [float(math.log(errs[i] / errs[i + 1]) / math.log(drs[i] / drs[i + 1]))
            for i in range(len(errs) - 1)]


def ladder_stats(rows):
    drs = [float(r["dr"]) for r in rows]
    errs = [float(r["l2_error"]) for r in rows]
    p, resid, se = ols(drs, errs)
    po = pair_orders(drs, errs)
    half = (max(po) - min(po)) / 2.0 if po else 0.0
    return {
        "fit_order": p,
        "least_squares_se": se,
        "lsq_residuals": resid,
        "pair_orders": po,
        "pair_half_range": half,
        "delta_R5": max(se, half),
        "monotone": all(errs[i + 1] < errs[i] for i in range(len(errs) - 1)),
        "within_band": bool(abs(p - P_EXPECTED) <= P_TOL),
        "n_rows": len(rows),
    }


def rel_dev(a, b):
    if a == b:
        return 0.0
    scale = max(abs(a), abs(b))
    return abs(a - b) / scale if scale > 0 else abs(a - b)


def compare_block(name, filed, fresh, out):
    """Compare a dict of recomputed statistics against the filed ones."""
    checks = []
    for key in ("fit_order", "least_squares_se", "pair_half_range", "delta_R5"):
        if key in filed:
            d = rel_dev(float(filed[key]), fresh[key])
            checks.append({"field": key, "filed": float(filed[key]),
                           "recomputed": fresh[key], "rel_dev": d,
                           "ok": d <= REL_TOL})
    if "pair_orders" in filed:
        d = max(rel_dev(float(a), float(b))
                for a, b in zip(filed["pair_orders"], fresh["pair_orders"])) \
            if filed["pair_orders"] else 0.0
        checks.append({"field": "pair_orders_max_rel_dev", "rel_dev": d,
                       "ok": d <= REL_TOL})
    if "monotone" in filed:
        checks.append({"field": "monotone", "filed": bool(filed["monotone"]),
                       "recomputed": fresh["monotone"],
                       "ok": bool(filed["monotone"]) == fresh["monotone"]})
    if "within_band" in filed:
        checks.append({"field": "within_band", "filed": bool(filed["within_band"]),
                       "recomputed": fresh["within_band"],
                       "ok": bool(filed["within_band"]) == fresh["within_band"]})
    ok = all(c["ok"] for c in checks)
    out[name] = {"ok": ok, "checks": checks}
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json-out", default=str(HERE / "verify_fixed_dt_control.json"))
    ap.add_argument("--skip-sweeps", action="store_true",
                    help="skip fresh re-run of the C temporal sweeps")
    ap.add_argument("--quick", action="store_true",
                    help="determinism/rerun on a 3-rung subset only (diagnostic use)")
    args = ap.parse_args()

    t0 = time.time()
    report = {
        "schema": "w020-n0-fixed-dt-control-verification/v1",
        "task_id": "W020-N0-FIXEDDT-VERIFY-01",
        "actor": "deepseek-flash-20",
        "class_id": "AF-WCC-SCALAR-SPH",
        "node_id": "N0",
        "gate": "G-NUM",
        "conclusion_type": "numerical_evidence",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "provenance": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "platform": platform.platform(),
            "host_pid": None,
        },
        "pins": {},
        "recomputation": {},
        "fresh_rerun": {},
        "rule_audit": {},
        "controls": {},
        "not_claimed": [
            "no gate verdict and no gate self-pass",
            "no node completion; numerics_lock stays LOCKED and numerics/spherical_solver/ is absent",
            "no edit to any canonical numerics/ or research_map/ path",
            "no physics claim; flat-space calibration evidence only",
            "no review verdict on any other artifact",
        ],
        "conflict_disclosure": (
            "worker-020 (deepseek-flash-20) is the original author of the unassigned candidate "
            "numerics/tests/flat_wave.py (sha256 8b52014dac47), which is NOT the target of this "
            "verification. The target is the lead's control artifact and the frozen replication "
            "module numerics/tests/flat_wave_replication.py (assignment deepseek-flash-13), "
            "neither authored by worker-020. The candidate is neither edited nor certified here."
        ),
    }

    # ---- hash guards -------------------------------------------------------
    for rel, exp in PINNED.items():
        p = REPO / rel
        got = sha256(p)
        report["pins"][rel] = {"expected": exp, "measured": got, "ok": got == exp}
        if got != exp:
            report["verdict"] = "VOID_STALE_PIN"
            Path(args.json_out).write_text(json.dumps(report, indent=2, sort_keys=True))
            print(json.dumps({"verdict": "VOID_STALE_PIN", "path": rel,
                              "expected": exp, "measured": got}, indent=2))
            return 2
    report["pins"]["generator"] = {
        "path": str(GENERATOR.relative_to(REPO)),
        "sha256": sha256(GENERATOR),
    }
    frozen, frozen_hash = load_frozen(PINNED["numerics/tests/flat_wave_replication.py"])
    target = json.loads(TARGET.read_text())
    report["target_summary"] = {
        "purpose": target.get("purpose"),
        "generator": target.get("provenance", {}).get("generator"),
        "generated_at": target.get("provenance", {}).get("generated_at"),
        "admissibility_rule": target.get("admissibility_rule_stated_before_results"),
        "overall": target.get("overall"),
    }

    # ---- A. recomputation from filed rows ---------------------------------
    recomp_ok = True
    for scheme, blk in target["schemes"].items():
        ladders = {"A_constant_cfl": blk["A_constant_cfl_ladder"]}
        for dt_key, lad in blk["B_fixed_dt_ladders"].items():
            ladders[f"B_{dt_key}"] = lad
        for lname, lad in ladders.items():
            fresh = ladder_stats(lad["rows"])
            ok = compare_block(f"{scheme}/{lname}", lad, fresh, report["recomputation"])
            recomp_ok = recomp_ok and ok
        # rule_a recomputation
        for dt_key, lad in blk["B_fixed_dt_ladders"].items():
            filed = blk["checks"].get(dt_key, {})
            gap = abs(lad["fit_order"] - blk["A_constant_cfl_ladder"]["fit_order"])
            row = {
                "filed_abs_gap": filed.get("abs_gap"),
                "recomputed_abs_gap": gap,
                "filed_rule_a_pass": filed.get("rule_a_pass"),
                "recomputed_rule_a_pass": bool(gap <= R5_FLOOR),
            }
            row["ok"] = (rel_dev(float(filed.get("abs_gap", gap)), gap) <= REL_TOL
                         and bool(filed.get("rule_a_pass")) == row["recomputed_rule_a_pass"])
            report["recomputation"][f"{scheme}/rule_a/{dt_key}"] = row
            recomp_ok = recomp_ok and row["ok"]
    report["recomputation_ok"] = recomp_ok

    # ---- B. fresh re-run of fixed-dt ladders ------------------------------
    dr_values = DR_VALUES if not args.quick else [0.2, 0.1, 0.05]
    fresh_ok = True
    for scheme, blk in target["schemes"].items():
        for dt_key, lad in blk["B_fixed_dt_ladders"].items():
            dt = float(lad["rows"][0]["dt"])
            study = frozen.order_study(scheme, dr_values=dr_values,
                                       dt_rule=(lambda dr, _dt=dt: _dt))
            filed_errs = {float(r["dr"]): float(r["l2_error"]) for r in lad["rows"]}
            rows = []
            for r in study["rows"]:
                fe = filed_errs.get(float(r["dr"]))
                dev = rel_dev(fe, float(r["l2_error"])) if fe is not None else None
                rows.append({"dr": float(r["dr"]), "dt": float(r["dt"]),
                             "steps": int(r["steps"]),
                             "filed_l2_error": fe, "fresh_l2_error": float(r["l2_error"]),
                             "rel_dev": dev})
            maxdev = max([r["rel_dev"] for r in rows if r["rel_dev"] is not None] or [0.0])
            pdev = rel_dev(float(lad["fit_order"]), float(study["fit_order"]))
            entry = {
                "max_row_rel_dev": maxdev,
                "fit_order_filed": float(lad["fit_order"]),
                "fit_order_fresh": float(study["fit_order"]),
                "fit_order_rel_dev": pdev,
                "rows": rows,
                "ok": maxdev <= REL_TOL and pdev <= REL_TOL,
            }
            report["fresh_rerun"][f"{scheme}/B/{dt_key}"] = entry
            fresh_ok = fresh_ok and entry["ok"]

    # determinism: re-run one point per scheme (dr=0.05) at both dt values
    det = {}
    for scheme in target["schemes"]:
        for dt in (1e-3, 5e-4):
            r = np.array(frozen.grid(R_MAX, 0.05))
            p = frozen.PulseExact()
            psi0, pt0, ptt0 = p.initial_data(r)
            vals = []
            for _ in range(2):
                s = frozen.SCHEMES[scheme][0](r, dt, psi0, pt0, ptt0)
                while s.t < T_END - 1e-12:
                    s.step()
                vals.append(float(frozen.l2_error(s.psi, p.psi(r, s.t), 0.05)))
            det[f"{scheme}/dt={dt}"] = {"a": vals[0], "b": vals[1],
                                        "bitwise_equal": vals[0] == vals[1]}
    report["determinism"] = {"points": det, "ok": all(v["bitwise_equal"] for v in det.values())}

    # ---- C. fresh re-run of temporal sweeps -------------------------------
    sweep_ok = True
    if not args.skip_sweeps:
        pulse = frozen.PulseExact()
        for scheme, blk in target["schemes"].items():
            for swee in blk["C_temporal_sweeps"]:
                dr = float(swee["dr"])
                pts = []
                for pt in swee["points"]:
                    dt = float(pt["dt"])
                    case = frozen.run_case(frozen.make_factory(scheme), dr, dt / dr,
                                           R_MAX, T_END)
                    err = float(frozen.l2_error(case["psi"][-1],
                                                pulse.psi(case["r"], case["t"][-1]), dr))
                    dev = rel_dev(float(pt["l2_error"]), err)
                    pts.append({"dt": dt, "filed": float(pt["l2_error"]), "fresh": err,
                                "rel_dev": dev, "ok": dev <= REL_TOL})
                maxdev = max(p["rel_dev"] for p in pts)
                entry = {"dr": dr, "points": pts, "max_rel_dev": maxdev,
                         "ok": maxdev <= REL_TOL}
                report["fresh_rerun"][f"{scheme}/C/dr={dr}"] = entry
                sweep_ok = sweep_ok and entry["ok"]
    report["fresh_rerun_ok"] = bool(fresh_ok and sweep_ok)

    # ---- D. rule audit -----------------------------------------------------
    rule_rows = {}
    for scheme, blk in target["schemes"].items():
        p_cfl = float(blk["A_constant_cfl_ladder"]["fit_order"])
        for dt_key, lad in blk["B_fixed_dt_ladders"].items():
            rule_rows.setdefault(dt_key, {})[scheme] = {
                "p_fixed": float(lad["fit_order"]),
                "p_cfl": p_cfl,
                "abs_gap": abs(float(lad["fit_order"]) - p_cfl),
                "rule_a_pass_as_written": bool(abs(float(lad["fit_order"]) - p_cfl) <= R5_FLOOR),
                "rule_a_pass_as_filed": blk["checks"].get(dt_key, {}).get("rule_a_pass"),
            }
    rule_b = {}
    for scheme, blk in target["schemes"].items():
        per_dr = {}
        for swee in blk["C_temporal_sweeps"]:
            e_at_cfl = float(swee["e_at_cfl"])
            e_plat = float(swee["e_plateau"])
            excess = e_at_cfl / e_plat - 1.0
            per_dr[str(swee["dr"])] = {
                "e_at_cfl": e_at_cfl, "e_plateau": e_plat,
                "excess": excess,
                "one_sided_pass_as_written": bool(excess <= 0.05),
                "symmetric_pass_abs_le_0.05": bool(abs(excess) <= 0.05),
            }
        worst_dr = max(per_dr, key=lambda k: per_dr[k]["excess"])
        rule_b[scheme] = {
            "per_dr": per_dr,
            "worst_dr": float(worst_dr),
            "worst_excess": per_dr[worst_dr]["excess"],
            "filed_rule_b_pass": blk["checks"].get("rule_b", {}).get("rule_b_pass"),
            "filed_rule_b_worst_dr": blk["checks"].get("rule_b", {}).get("dr_of_worst"),
            "filed_verdict": blk["verdict"],
            "filed_admissible_as_spatial": blk["checks"].get("admissible_as_spatial"),
        }
    stated = target["admissibility_rule_stated_before_results"]
    report["rule_audit"] = {
        "rule_a_as_written": "|p_fixed_dt - p_cfl| <= 0.25 (R5 floor)",
        "rule_a": rule_rows,
        "rule_b_as_written": stated.get("rule_b"),
        "rule_b_recomputed": rule_b,
        "spec_vs_implementation": {
            "rule_b_text_says_dr": 0.2,
            "filed_rule_b_reports_worst_over_dr": True,
            "one_sided": "the written rule is one-sided (excess <= 0.05); a negative excess "
                         "(constant-CFL error BELOW the spatial plateau: temporal-spatial "
                         "cancellation) passes without bound",
        },
    }

    # ---- E. controls -------------------------------------------------------
    ctl = frozen.controls()
    nullp = float(ctl["frozen_state"]["fit_order"])
    # mutation control on our own recomputation
    mut = json.loads(json.dumps(target))
    mutated_key = None
    for scheme, blk in mut["schemes"].items():
        for dt_key, lad in blk["B_fixed_dt_ladders"].items():
            lad["rows"][0]["l2_error"] = float(lad["rows"][0]["l2_error"]) * (1.0 + 1e-6)
            mutated_key = f"{scheme}/B/{dt_key}/row0"
            break
        break
    mut_detected = False
    for scheme, blk in mut["schemes"].items():
        for dt_key, lad in blk["B_fixed_dt_ladders"].items():
            fresh = ladder_stats(lad["rows"])
            for c in ("fit_order", "pair_half_range", "delta_R5"):
                if rel_dev(float(lad[c]), fresh[c]) > REL_TOL:
                    mut_detected = True
    report["controls"] = {
        "frozen_state_null": {
            "fit_order": nullp,
            "rejected_by_order_gate": bool(ctl["frozen_state"]["rejected_by_order_gate"]),
            "ok": bool(abs(nullp) < 0.5 and ctl["frozen_state"]["rejected_by_order_gate"]),
        },
        "wrong_sign_operator": ctl["wrong_sign_operator"],
        "dt_probe_mixed_order": ctl["dt_probe_dt_eq_dr_pow_half"],
        "mutation_control": {"mutated": mutated_key, "detected": bool(mut_detected),
                             "ok": bool(mut_detected)},
    }

    # ---- F. verdict --------------------------------------------------------
    b_ladder_orders = {
        dt_key: {scheme: blk["B_fixed_dt_ladders"][dt_key]["fit_order"]
                 for scheme, blk in target["schemes"].items()}
        for dt_key in list(next(iter(target["schemes"].values()))["B_fixed_dt_ladders"])
    }
    all_b_within_band = all(
        abs(float(blk["B_fixed_dt_ladders"][dt_key]["fit_order"]) - P_EXPECTED) <= P_TOL
        for blk in target["schemes"].values() for dt_key in blk["B_fixed_dt_ladders"])
    report["verdict"] = {
        "status": "VERIFIED_WITH_ONE_RULE_DEFECT" if (recomp_ok and report["fresh_rerun_ok"]
                                                       and all_b_within_band) else "FAILED",
        "filed_statistics_recompute": bool(recomp_ok),
        "fixed_dt_ladders_independently_reproduced": bool(fresh_ok),
        "temporal_sweeps_independently_reproduced": bool(sweep_ok),
        "determinism_bitwise": bool(report["determinism"]["ok"]),
        "controls_ok": bool(all(v.get("ok", True) for v in report["controls"].values()
                                if isinstance(v, dict))),
        "fixed_dt_ladder_orders": b_ladder_orders,
        "fixed_dt_ladders_all_within_band": bool(all_b_within_band),
        "finding_RB1": (
            "rule_b is one-sided as pre-registered: constant-CFL errors below the spatial "
            "plateau (negative excess, temporal-spatial cancellation) pass. Symmetric "
            "magnitudes at the finest sweep dr: "
            + ", ".join(f"{s}={abs(rule_b[s]['per_dr'][max(rule_b[s]['per_dr'], key=lambda k: abs(rule_b[s]['per_dr'][k]['excess']))]['excess']):.3f}"
                        for s in rule_b)
            + ". The filed per-scheme verdicts for the schemes that pass describe the order as "
              "measured, but the parenthetical 'temporal contribution below tolerance' holds "
              "only in the one-sided reading."
        ),
        "finding_RB2": (
            "the written rule names dr=0.2, the filed check reports the worst over "
            "temporal_dr=[0.2, 0.05]; applying the rule at the worst dr is stricter and does "
            "not change any pass/fail here."
        ),
        "c8_disposition": (
            "The order-2 spatial conclusion IS supported by the protocol-compliant fixed-dt "
            "ladders B at both dt=1e-3 and dt=5e-4 for all three schemes, and this verification "
            "reproduces every B row at the pinned frozen-module hash. The constant-CFL ladder A "
            "should be cited only as a labelled mixed-order supporting control, and rule_b "
            "should be restated symmetrically before this artifact is used as G-NUM C8 evidence."
        ),
    }
    report["falsifier"] = (
        "Void if: (i) either pinned input re-hashes differently; (ii) a fresh re-run at frozen "
        "module 8ade1cdc reproduces any filed fixed-dt B row outside 1e-9 relative; (iii) a "
        "filed B ladder fit order falls outside |p-2|<=0.3; (iv) a filed derived statistic "
        "differs from this script's recomputation by more than 1e-9 relative; or (v) the "
        "mutation control is not detected."
    )
    report["runtime_seconds"] = round(time.time() - t0, 2)
    out = Path(args.json_out)
    out.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps({
        "verdict": report["verdict"]["status"],
        "recomputation_ok": recomp_ok,
        "fresh_rerun_ok": report["fresh_rerun_ok"],
        "fixed_dt_ladder_orders": b_ladder_orders,
        "runtime_seconds": report["runtime_seconds"],
        "json_out": str(out),
    }, indent=2, sort_keys=True))
    return 0 if report["verdict"]["status"] != "FAILED" else 1


if __name__ == "__main__":
    raise SystemExit(main())
