#!/usr/bin/env python3
"""Compare the two F0 candidate taxonomies (review HF-07) to speed canonical designation.

Writes artifacts/worker-01/F0_candidate_diff.md and .json. Read-only: touches neither candidate.
  python3 artifacts/worker-01/render_f0_candidate_diff.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
A_PATH = ROOT / "research_map" / "formulation_taxonomy.yaml"
B_PATH = ROOT / "artifacts" / "formulation" / "formulation_taxonomy.yaml"
OUT_MD = ROOT / "artifacts" / "worker-01" / "F0_candidate_diff.md"
OUT_JSON = ROOT / "artifacts" / "worker-01" / "F0_candidate_diff.json"
FROZEN = ["AF-WCC-VAC-GEN", "AF-SCC-C2-VAC-GEN", "AF-SCC-C0-VAC-GEN", "AF-WCC-SCALAR-SPH"]


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def a_view(d):
    return {cid: {"axes": d["classes"][cid]["axes"],
                  "conclusion_type": d["classes"][cid]["axes"]["conclusion_type"],
                  "conclusion_text": d["classes"][cid]["conclusion"]["text"].strip(),
                  "exclusions_n": len(d["classes"][cid]["exclusions"])} for cid in FROZEN}


def b_view(d):
    return {cid: {"axes": d["class_contracts"][cid].get("components", {}),
                  "conclusion_type": d["class_contracts"][cid].get("conclusion_type"),
                  "conclusion_text": d["class_contracts"][cid].get("conclusion_predicate"),
                  "exclusions_n": len(d["class_contracts"][cid].get("exclusions", []))} for cid in FROZEN}


def main():
    A, B = yaml.safe_load(A_PATH.read_text()), yaml.safe_load(B_PATH.read_text())
    av, bv = a_view(A), b_view(B)
    rows = []
    conflicts = []
    for cid in FROZEN:
        ct_match = av[cid]["conclusion_type"] == bv[cid]["conclusion_type"]
        if not ct_match:
            conflicts.append(f"{cid}: conclusion_type {av[cid]['conclusion_type']} vs {bv[cid]['conclusion_type']}")
        rows.append(f"| `{cid}` | {av[cid]['conclusion_type']} | {bv[cid]['conclusion_type']} | "
                    f"{'match' if ct_match else '**conflict**'} | {json.dumps(av[cid]['axes'], sort_keys=True)} | "
                    f"{json.dumps(bv[cid]['axes'], sort_keys=True)} |")
    both_freeze = (set(A.get("class_ids", [])) == set(B.get("frozen_classes", [])) == set(FROZEN))
    md = f"""# F0 candidate diff (review HF-07) -- decision input for lead-formulation / Astra

Read-only comparison generated by worker-01. Neither file is modified by this report.

| candidate | path | sha256 | author | canonical flag |
|---|---|---|---|---|
| A (worker-01) | `research_map/formulation_taxonomy.yaml` | `{sha(A_PATH)}` | deepseek-flash-01 (assigned main author) | none; awaiting designation |
| B (lead, remediation) | `artifacts/formulation/formulation_taxonomy.yaml` | `{sha(B_PATH)}` | astra-lead-formulation | `remediation: true`, `review_status.verdict: pending` |

Both freeze the same four class ids: **{both_freeze}**.
Decision needed: designate ONE canonical F0 artifact and record its sha256 in the map; mark the other
superseded (review HF-07 fix). Until then F1/F2 reviewers cannot know which class semantics bind.

## Per-class comparison

| class | A conclusion_type | B conclusion_type | verdict | A axes | B components |
|---|---|---|---|---|---|
{chr(10).join(rows)}

## Vocabulary mapping (review finding 3)

| A value | B value | action |
|---|---|---|
| `weak_cosmic_censorship` | `weak_cosmic_censorship` | already aligned |
| `strong_cosmic_censorship_C2` | `scc_c2_future_inextendibility` | pick one; both artifacts must use it |
| `strong_cosmic_censorship_C0` | `scc_c0_future_inextendibility` | pick one; both artifacts must use it |

## WCC predicate

- A (rev2): "MGHD admits a conformal completion with a complete future null infinity I+ (all null
  generators complete), and every future-inextendible causal geodesic contained in J-(I+) is
  complete. Visibility is defined by that condition ... not an asserted equivalence."
- B: "{bv['AF-WCC-VAC-GEN']['conclusion_text']}"
- B `non_goals` includes black-hole formation; A now lists the black-hole-region statement only in
  `candidate_consequences.C1` as unresolved. The two candidates have converged on this point.

## Process consequence if B is designated canonical

Worker-01's checkers are written against A's flat `classes[cid].axes` layout. They do **not** silently
apply to B; the formulation lead should either (a) request an adapter that binds B's `class_contracts`
to the same checks, or (b) designate A. The F0 author will not edit B.

## Escalation record

- `comms/outbox/deepseek-flash-01.jsonl` status event with `needs_designation: true`
- reviewers: w17 (`reviews/F0-F1-review-17.json`), lead-audit (`reviews/F0-review-lead-audit.json`)

Generated from A sha `{sha(A_PATH)[:12]}` and B sha `{sha(B_PATH)[:12]}`.
"""
    OUT_MD.write_text(md)
    OUT_JSON.write_text(json.dumps({
        "a": {"path": str(A_PATH.relative_to(ROOT)), "sha256": sha(A_PATH)},
        "b": {"path": str(B_PATH.relative_to(ROOT)), "sha256": sha(B_PATH)},
        "both_freeze_same_ids": both_freeze,
        "conclusion_type_conflicts": conflicts,
        "a_view": av, "b_view": bv,
    }, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUT_MD} ({len(conflicts)} conclusion-type conflicts)")


if __name__ == "__main__":
    main()
