#!/usr/bin/env python3
"""Render artifacts/worker-01/F0_ACCEPTANCE_EVIDENCE.md from the taxonomy + validator report.

Reproducible: re-run after any validator revision so the quoted hashes and counts cannot drift.
  python3 artifacts/worker-01/render_f0_evidence.py
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
CST = timezone(timedelta(hours=8))
TAX = ROOT / "research_map" / "formulation_taxonomy.yaml"
VAL = ROOT / "artifacts" / "worker-01" / "validate_taxonomy.py"
REP = ROOT / "artifacts" / "worker-01" / "taxonomy_validation.json"
OUT = ROOT / "artifacts" / "worker-01" / "F0_ACCEPTANCE_EVIDENCE.md"


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    now = datetime.now(CST).isoformat(timespec="seconds")
    tax = yaml.safe_load(TAX.read_text())
    rep = json.loads(REP.read_text())
    H = {"tax": sha(TAX), "val": sha(VAL), "rep": sha(REP)}
    groups = rep.get("checks_passed_by_group", {})
    h_count = sum(v for k, v in groups.items() if k == "H" or k.startswith("H["))
    rows = []
    for cid, c in tax["classes"].items():
        ax = c["axes"]
        rows.append(
            f"| `{cid}` | {ax['family']} | {ax['regularity_token'] or '-'} | {ax['matter_model']} | "
            f"{ax['symmetry']} | {ax['conclusion_type']} | {len(c['hypotheses'])} | {len(c['exclusions'])} | "
            f"{c['test_cases']['positive']['id']} | {c['test_cases']['negative']['id']} |"
        )
    md = f"""# F0 / gate G-F0 acceptance evidence (advisory, machine-checked, no reviewer verdict yet)

Generated by worker-01 (`deepseek-flash-01`) at {now} for the G-F0 reviewer queue (A1 targets 17/19).
This file is evidence for review; it is **not** a completion claim and **not** a review verdict.

## Artifact under review

- path: `research_map/formulation_taxonomy.yaml`
- sha256: `{H['tax']}`
- revision {tax.get('revision')}, status `{tax.get('status')}`, `claims_theorem_status: {str(tax.get('claims_theorem_status')).lower()}`
- machine acceptance: **{rep['checks_passed']} passed / {rep['checks_failed']} failed** ({rep['verdict']}) -- author self-check, discounted for G-F0 (review finding 4)

## G-F0 criteria (from `research_map.json#gates`) -> evidence

| criterion | evidence | status |
|---|---|---|
| file exists | `research_map/formulation_taxonomy.yaml`, sha256 above | met |
| exactly 4 separate class ids | checker A: `class_ids` and `classes` keys equal the frozen set | met |
| disjointness tests | checker D: all 6 pairs present; each pair's named decisive axes actually differ in value | met |
| each class has hypotheses, exclusions, conclusion_type, +1/-1 test case | checker B | met |
| "class overlap on a test case" falsifier | checker I: 27 checks over 12 inline cases; every case names a decisive hypothesis that exists and lands in exactly one class or an explicit `excluded_by:`/`rejected_by:` reason | met |
| worker-02 adversarial corpus consumed independently | checker H: {h_count} assertions over {rep['cases_checked']} corpus rows; meta polarity counts agree; every `CLASS:Hx` reference resolves; 3 planted out-of-vocabulary negatives (`COMPOSITE_C0_C2`, `COMPOSITE_WCC_SCC`) are accepted only because they are the defect under test | met |
| 2 independent reviewer verdicts | `reviews/F0-F1-review-17.json` (w17, revise 3.0) and `reviews/F0-review-lead-audit.json` (lead-audit, revise 3.0) | **revise, addressed in rev2; re-review required** |

## Review responses (revision 2)

| review | finding | action in rev2 |
|---|---|---|
| w17 | 2 critical: black-hole-region clause asserted as equivalent | removed from the conclusion; moved to `candidate_consequences.C1` as `unresolved_pending_L0_L1`, explicitly not a classification predicate |
| w17 | 5 major: C0 mislabelled "higher regularity token" | reworded to "a stronger conclusion at lower regularity (C0)" |
| w17 | 6 major: G3 misses `C^{{0}} or C^{{2}}` spellings | checker normalizes ^ {{ }} _ and whitespace; 5th self-test mutation covers the braced spelling |
| w17 | 8 minor: electrovacuum claim inside exclusions | moved to `known_obstruction` as an unresolved literature pointer |
| w17 | 9 minor: provisional genericity read as frozen | axes now carry `provisional_baire_residual`; vocabulary documents `provisional_*` as non-frozen |
| w17 | 10 minor: content timestamp ahead of mtime | `created_at` + observed `written_at` + `timestamp_provenance` |
| lead-audit | HF-02 critical: `meaning_C2` reversed the containment (C2 subset of C^{{1,1}}/H^2_loc) | corrected: forbidding C2 forbids only C2 and smoother classes, NOT C^{{1,1}}/H^2_loc |
| lead-audit | HF-06 major: genericity axes provisional | as w17-9 |
| lead-audit | HF-06 major: unsourced equivalence + B-interior | visibility restated as a definition; B-interior in `candidate_consequences` |
| lead-audit | HF-04 major: disjointness read as data-space disjointness | comment + F0-N7 wording: disjointness is descriptor-level; data sets may overlap (Schwarzschild solves the scalar system with phi=0) |
| w17 | 1 critical HF-07: two divergent F0 candidates | **escalated**: needs lead-formulation/Astra designation; see `artifacts/worker-01/F0_candidate_diff.md` |
| w17 | 3 major: conclusion-type vocabularies differ | **escalated**: F0 freezes `strong_cosmic_censorship_C2/_C0`; F0-R uses `scc_c2_future_inextendibility`; one must be chosen |
| w17 | 4 major: self-validation only | acknowledged; reviewer verdicts recorded in `provenance.reviewer_verdicts` |
| w17 | 7 minor: F0-R violates its own composite ban | not this artifact; reported to lead-formulation for F0-R |

## Class table (generated from the artifact)

| class | family | token | matter | symmetry | conclusion_type | #hyp | #excl | +case | -case |
|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

Each class also carries `negative_2` where a second exclusion mode is needed (genericity exclusion,
conclusion-inflation direction, symmetry release).

## Machine acceptance and control

```
$ python3 artifacts/worker-01/validate_taxonomy.py --json artifacts/worker-01/taxonomy_validation.json
{{"checks_passed": {rep['checks_passed']}, "checks_failed": {rep['checks_failed']}, "cases_checked": {rep['cases_checked']}, "verdict": "{rep['verdict']}"}}

$ python3 artifacts/worker-01/validate_taxonomy.py --self-test
baseline_passes: true; planted defects caught: 4/4 (token/class-id mismatch, same-value disjointness
axis, merged-regularity in semantic content, self-classified negative case)
```

Validator sha256: `{H['val']}`; validation report sha256: `{H['rep']}`.

## Reviewer checklist: independent falsification attempts (each should FAIL the checker)

1. copy the file to /tmp; set `AF-SCC-C2-VAC-GEN.axes.regularity_token: C0` -> checker must fail (`C[C2]: regularity_token matches the token in the class id`).
2. delete one class's `exclusions` list -> checker must fail (`B[...]: exclusions present and non-empty`).
3. rename one class key -> checker must fail (identity check A).
4. inject the merged-regularity phrase into a `conclusion.text` -> checker must fail (F, G3 on semantic content).
5. hand-classify the twelve inline test cases (F0-P1..P4, F0-N1..N8): each must land in exactly one class or carry an explicit `excluded_by:` reason. A case landing in two classes is the F0 falsifier firing -- report it rather than fixing the case.
6. `schemas/taxonomy_cases.jsonl` (worker-02) is consumed by default: `python3 artifacts/worker-01/validate_taxonomy.py` runs checker H over all {rep['cases_checked']} rows. `--cases <path>` points the same checks at an alternative corpus.
7. reproduce the corpus-consumer judgement on the three non-frozen filed ids (`COMPOSITE_C0_C2`, `COMPOSITE_C0_C2`, `COMPOSITE_WCC_SCC`): they must pass only as negative cases carrying `violated_vocabulary` or an `expected_leak_rule`; if one is re-filed as positive, the checker must fail.

## Deliberately unresolved (not defects)

- genericity kind/topology and weighted Sobolev parameters `s`, `delta`: owned by F1/F2, marked `unresolved` in the artifact.
- every literature pointer is `unresolved_pending_L1`; no statement is asserted as a theorem or counterexample.
- `coverage_gaps.CG1`: `AF-WCC-SCALAR-SPH` has no F-node/schema owner in the current map.

## Known adjacent observations (not part of F0 acceptance)

- A raw-text G3 scan false-positives on this file's own guard/prohibition sections; the checker scans
  structured semantic content only. Downstream linters should do the same.
- `schemas/af_scc_c0_vacuum.yaml` line 5 contains the forbidden phrase inside a comment
  ("Never write ..."); a raw-text linter will flag it, a semantic-field linter will not.
- F1/F2 field names currently differ from `field_vocabulary` slot names (crosswalk pending);
  the taxonomy's vocabulary is a normative rule for downstream schemas, so this is a G-FORM
  question for the formulation lead, not an F0 defect.

## Provenance

- comms/inbox/deepseek-flash-01.jsonl#asg-2026-09-11-F0-deepseek-flash-01-10
- research_map/ASTRA_HANDOFF.md:30
- runtime/state/checkpoint_log.jsonl#ckpt-20260911-231750
- Note: outbox event ids carrying `T2332` use an approximate clock label; each event's `created_at` is authoritative.
"""
    OUT.write_text(md)
    print(f"wrote {OUT}")
    print(json.dumps(H, indent=1))


if __name__ == "__main__":
    main()
