#!/usr/bin/env python3
"""Build ledger/class_coverage.csv (worker flash-10, node L1).

Inputs (all in artifacts/flash-10/l1_class_coverage/):
  sources.json   -- verified arXiv metadata registry (generated by fetch_sources.py)
  class_map.json -- hand-checked curation: which source covers which frozen class

Outputs:
  <repo>/ledger/class_coverage.csv        -- the assigned artifact (source x class matrix)
  coverage_summary.json                   -- counts + the empty cells (the interesting output)

Determinism: rows are ordered by source key then by frozen class order; no timestamps are
put inside the CSV so its hash is reproducible from the inputs.
"""
from __future__ import annotations

import csv
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]  # /.../ai4math-swarm
OUT_CSV = ROOT / "ledger" / "class_coverage.csv"
SUMMARY = HERE / "coverage_summary.json"

CLASSES = ["AF-WCC-VAC-GEN", "AF-SCC-C2-VAC-GEN", "AF-SCC-C0-VAC-GEN", "AF-WCC-SCALAR-SPH"]
CLASS_REG = {"AF-WCC-VAC-GEN": "n/a", "AF-SCC-C2-VAC-GEN": "C^2",
             "AF-SCC-C0-VAC-GEN": "C^0", "AF-WCC-SCALAR-SPH": "n/a"}
COLUMNS = ["row_id", "source_key", "citation", "authors", "year", "locator_arxiv", "locator_doi",
           "journal_ref", "local_source_path", "local_source_sha256", "class_id", "coverage", "role",
           "conclusion_type_stated", "regularity", "genericity_stated", "exact_theorem",
           "theorem_locator", "scope_match", "basis", "verification_status", "assumptions",
           "falsifier", "ledger_row_id", "notes"]


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def norm_arxiv(raw: str) -> str:
    m = re.search(r"(?:abs/)?((?:[a-z-]+(?:\.[A-Z]{2})?/\d{7})|\d{4}\.\d{4,5})(v\d+)?", raw or "")
    return m.group(1) if m else (raw or "")


def join(x) -> str:
    if isinstance(x, list):
        return " | ".join(str(i) for i in x)
    return "" if x is None else str(x)


def main() -> int:
    reg = json.loads((HERE / "sources.json").read_text())
    cmap = json.loads((HERE / "class_map.json").read_text())
    classes = cmap["frozen_classes"]
    assert classes == CLASSES, f"frozen class order changed: {classes}"

    curated = cmap["sources"]
    boundary = cmap["boundary_only"]["sources"]
    unresolved = cmap["unresolved_sources"]["sources"]
    local = cmap["local_sources"]

    rows = []

    def add(source_key, citation, authors, year, arxiv, doi, jref, lpath, lhash, cls, cov, role,
            ctype, reg, gen, thm, tloc, scope, basis, vstatus, assum, fals, notes):
        rows.append({"row_id": "", "source_key": source_key, "citation": citation, "authors": authors,
                     "year": year, "locator_arxiv": arxiv, "locator_doi": doi, "journal_ref": jref,
                     "local_source_path": lpath, "local_source_sha256": lhash, "class_id": cls,
                     "coverage": cov, "role": role, "conclusion_type_stated": ctype, "regularity": reg,
                     "genericity_stated": gen, "exact_theorem": thm, "theorem_locator": tloc,
                     "scope_match": scope, "basis": basis, "verification_status": vstatus,
                     "assumptions": assum, "falsifier": fals, "ledger_row_id": "", "notes": notes})

    # 1) registry sources with a verified selection
    for s in reg["sources"]:
        key = s.get("matrix_key", s["key"])
        sel = s.get("selected")
        if not sel:
            continue
        citation = f"{', '.join(sel['authors'][:4])}{' et al.' if len(sel['authors']) > 4 else ''}. {sel['title']}."
        year = (sel.get("published") or "")[:4]
        arxiv = norm_arxiv(sel.get("arxiv_id", ""))
        doi = "" if (sel.get("doi") or "-") == "-" else sel["doi"]
        jref = "" if (sel.get("journal_ref") or "-") == "-" else sel["journal_ref"]
        hint = s.get("class_hint", "")
        for cls in classes:
            hit = next((r for r in curated.get(key, []) if r["class_id"] == cls), None)
            if hit:
                add(key, citation, join(sel["authors"]), year, arxiv, doi, jref, "", "", cls,
                    hit["coverage"], hit["role"], hit["conclusion_type_stated"], hit["regularity"],
                    hit.get("genericity_stated", ""), hit["exact_theorem"], hit["theorem_locator"],
                    hit["scope_match"], hit["basis"], hit["verification_status"],
                    join(hit.get("assumptions", [])), join(hit.get("falsifier", "")), hit.get("notes", ""))
            else:
                note = ("empty cell: verified source has no conclusion of this class's type; "
                        f"registry class_hint={hint or 'n/a'}.")
                if key in boundary:
                    note = f"boundary/out-of-class: {boundary[key]}"
                add(key, citation, join(sel["authors"]), year, arxiv, doi, jref, "", "", cls,
                    "none", "boundary_case" if key in boundary else "out_of_class",
                    "not_applicable", CLASS_REG[cls], "", "", "n/a", "mismatch",
                    "primary_abstract", "verified_metadata", "", "", note)

    # 2) local primary sources
    for key, meta in local.items():
        paths = [Path(p) if Path(p).is_absolute() else ROOT / p for p in meta["paths"]]
        rel = [str(p.relative_to(ROOT)) for p in paths]
        hashes = [sha256(p) for p in paths if p.exists()]
        for cls in classes:
            hit = next((r for r in meta["rows"] if r["class_id"] == cls), None)
            if hit:
                add(key, meta["citation"], meta["authors"], meta["year"], "", "", meta.get("journal_ref", ""),
                    join(rel), join(hashes), cls, hit["coverage"], hit["role"],
                    hit["conclusion_type_stated"], hit["regularity"], hit.get("genericity_stated", ""),
                    hit["exact_theorem"], hit["theorem_locator"], hit["scope_match"], hit["basis"],
                    hit["verification_status"], join(hit.get("assumptions", [])),
                    join(hit.get("falsifier", "")), hit.get("notes", ""))
            else:
                add(key, meta["citation"], meta["authors"], meta["year"], "", "", meta.get("journal_ref", ""),
                    join(rel), join(hashes), cls, "none", "out_of_class", "not_applicable",
                    CLASS_REG[cls], "", "", "n/a", "mismatch", "primary_local", "verified_local", "", "",
                    "empty cell: local primary source has no conclusion of this class's type.")

    # 3) unresolved slots (explicitly unassessed, never 'none')
    for key, meta in unresolved.items():
        for cls in classes:
            add(key, f"[LOCATOR UNRESOLVED] {key}", "", "", "", "", "", "", "", cls, "unassessed",
                "unresolved_locator", "not_applicable", CLASS_REG[cls], "", "", "n/a", "mismatch",
                "unverified", "unresolved", "", meta["next_falsifier"],
                f"unassessed: locator could not be verified in this run. attempted={meta['attempted']}; why={meta['why']}")

    for i, r in enumerate(rows, 1):
        r["row_id"] = f"CC-{i:04d}"

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)

    # summary: the empty cells are the deliverable
    summary = {"csv": str(OUT_CSV.relative_to(ROOT)), "rows": len(rows),
               "sources": len({r["source_key"] for r in rows}),
               "classes": {}, "coverage_totals": {}, "zero_covered_classes": [],
               "zero_partial_or_better_classes": [], "unassessed_sources": sorted(unresolved),
               "verified_locator_sources": sorted({r["source_key"] for r in rows
                                                   if r["verification_status"] in {"verified_metadata", "verified_local"}})}
    for cls in classes:
        sub = [r for r in rows if r["class_id"] == cls]
        counts = {c: sum(1 for r in sub if r["coverage"] == c) for c in
                  ["covered", "partial", "none", "unassessed"]}
        summary["classes"][cls] = counts
        if counts["covered"] == 0:
            summary["zero_covered_classes"].append(cls)
        if counts["covered"] + counts["partial"] == 0:
            summary["zero_partial_or_better_classes"].append(cls)
    for c in ["covered", "partial", "none", "unassessed"]:
        summary["coverage_totals"][c] = sum(1 for r in rows if r["coverage"] == c)
    SUMMARY.write_text(json.dumps(summary, indent=2) + "\n")

    print(f"wrote {OUT_CSV} ({len(rows)} rows, {summary['sources']} sources)")
    print(f"coverage totals: {summary['coverage_totals']}")
    for cls in classes:
        print(f"  {cls:20s} {summary['classes'][cls]}")
    print(f"classes with ZERO covered cells: {summary['zero_covered_classes']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
