#!/usr/bin/env python3
"""W053-A1-COVERAGE-VALIDITY-01 -- independent validity census of the A1 review-coverage scan.

Question this answers, at one pinned snapshot:
  Does `astra_lifecycle.review_coverage` -- the authoritative instrument behind the
  G-F0 / G-FORM / G-AUDIT "distinct accept reviewer(s)" counts -- report a census
  that survives (a) same-reviewer self-amendment at one target+hash and
  (b) path-form target ids for canonical artifacts?

Method: deterministic, read-only, stdlib-only.
  V1  pin every canonical artifact by hashing it in-run (single-read), plus the
      module file that defines the scan policy.
  V2  import `astra_lifecycle` and call its `review_coverage` -- authoritative output.
  V3  independently reimplement the documented policy and require exact agreement
      with V2 on the (file, reviewer, verdict, full) entry set per target.
  V4  detect reviewers holding more than one bound verdict of differing kind on the
      SAME target at the SAME hash; order by (created_at, filename) and derive the
      corrected accept-reviewer set.
  V5  tabulate raw vs corrected distinct-accept counts.
  V6  detect reviews whose target is a canonical artifact PATH (optionally with a
      '#fragment'/'#sha256:' suffix): these are never normalised to a node id, so
      they are invisible to V2 no matter what hash they pin. Classify each by
      whether its explicit pin reaches the current canonical hash.
  V7  confirm scoped verdicts (counts_as_full_schema_verdict=false) are excluded.
  V8  compare V2 against the recorded controller_gate_audit counts, and state the
      structural limit: the recorded reason is generated by the same scan, so it
      reproduces V2's blind spots rather than detecting them.

Controls K1..K8 are planted defects exercised through the SAME predicate functions
used in V3-V7, in a sandbox corpus; they are not a test of `astra_lifecycle`.

Authority: this is a measurement report. It sets no gate verdict, no node status,
and no validation_status. Worker verdicts are advisory evidence only.

Usage:  python3 check_a1_coverage_validity.py [--out DIR]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent          # artifacts/worker-053/<task>/ -> repo root
CST = timezone(timedelta(hours=8))
REVIEWS = ROOT / "reviews"

TASK_ID = "W053-A1-COVERAGE-VALIDITY-01"
ACTOR = "worker-053"
CLASS_IDS = ["AF-WCC-VAC-GEN", "AF-SCC-C2-VAC-GEN", "AF-SCC-C0-VAC-GEN"]
NODE_ID = "A1"
GATE = "G-AUDIT"

# Canonical artifacts for every node the coverage scan can score. Paths taken from
# research_map.json group/node records; hashes are measured in-run (V1), never trusted.
TARGET_PATHS = {
    "F0": "research_map/formulation_taxonomy.yaml",
    "F1": "schemas/af_wcc_vacuum.yaml",
    "F2a": "schemas/af_scc_c2_vacuum.yaml",
    "F2b": "schemas/af_scc_c0_vacuum.yaml",
    "L0": "ledger/theorems.jsonl",
    "L1": "ledger/citation_audit.csv",
}

VERDICT_KINDS = ("accept", "revise", "reject", "inconclusive")
TARGET_ALIASES = {
    "F0": "F0", "F1": "F1", "F2A": "F2a", "F2B": "F2b", "F2": "F2b",
    "L0": "L0", "L1": "L1",
    "AF-WCC-VAC-GEN": "F1",
    "AF-SCC-C2-VAC-GEN": "F2a",
    "AF-SCC-C0-VAC-GEN": "F2b",
}
ARTIFACT_SUFFIXES = (".yaml", ".yml", ".json", ".jsonl", ".csv", ".md", ".txt")
PIN_KEYS = ("artifact_sha256", "reviewed_sha256", "sha256", "cited_sha256")


def now() -> str:
    return datetime.now(CST).isoformat(timespec="seconds")


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# --------------------------------------------------------------------------- policy
def targets_in_review(d: dict) -> set:
    """Reimplementation of astra_lifecycle._targets_in_review (V3 cross-checks it)."""
    out = set()
    for key in ("target_id", "target", "target_subnode"):
        v = d.get(key)
        if isinstance(v, str):
            out.add(v)
        elif isinstance(v, dict):
            for k2 in ("target_id", "target_subnode", "subnode", "node_id"):
                if isinstance(v.get(k2), str):
                    out.add(v[k2])
    norm = set()
    for t in out:
        norm.add(TARGET_ALIASES.get(t, TARGET_ALIASES.get(t.upper(), t)))
    return norm


def raw_targets(d: dict) -> list:
    out = []
    for key in ("target_id", "target", "target_subnode"):
        v = d.get(key)
        if isinstance(v, str):
            out.append(v)
        elif isinstance(v, dict):
            for k2 in ("target_id", "target_subnode", "subnode", "node_id"):
                if isinstance(v.get(k2), str):
                    out.append(v[k2])
    return out


def explicit_pins(d: dict) -> list:
    """Reimplementation of astra_lifecycle._explicit_pins."""
    pins = []
    for key in PIN_KEYS:
        v = d.get(key)
        if isinstance(v, str):
            pins.append(v.lower())
    for key in ("target", "artifact"):
        v = d.get(key)
        if isinstance(v, dict):
            for k2 in ("sha256", "artifact_sha256", "reviewed_sha256"):
                if isinstance(v.get(k2), str):
                    pins.append(v[k2].lower())
    return pins


def pin_matches(pin: str, h: str) -> bool:
    """Reimplementation of the scan's prefix predicate."""
    return bool(pin) and bool(h) and (pin.startswith(h[:12]) or h.startswith(pin[:12]))


def scan(hashes: dict, reviews_dir: Path) -> dict:
    """Independent scan. Returns per-target entries with timestamps for V4."""
    cov = {t: [] for t in hashes}
    for rp in sorted(reviews_dir.glob("*.json")):
        try:
            d = json.loads(rp.read_text())
        except Exception:
            continue
        if not isinstance(d, dict):
            continue
        v = str(d.get("verdict", "")).lower()
        if v not in VERDICT_KINDS:
            continue
        reviewer = str(d.get("reviewer") or d.get("actor") or "?")
        full = d.get("counts_as_full_schema_verdict") is not False
        pins = explicit_pins(d)
        for t in targets_in_review(d):
            if t not in cov:
                continue
            h = hashes.get(t, {}).get("sha256") or ""
            if any(pin_matches(p, h) for p in pins):
                cov[t].append({
                    "file": rp.name, "reviewer": reviewer, "verdict": v,
                    "counts_as_full_schema_verdict": full,
                    "created_at": str(d.get("created_at") or ""),
                    "mtime": datetime.fromtimestamp(rp.stat().st_mtime, CST).isoformat(timespec="seconds"),
                })
    return cov


def distinct_accepts(entries: list) -> list:
    return sorted({e["reviewer"] for e in entries
                   if e["verdict"] == "accept" and e["counts_as_full_schema_verdict"]})


def corrected_accepts(entries: list) -> tuple:
    """Reviewer's latest bound verdict at this target+hash wins (self-amendment)."""
    by_rev = {}
    for e in entries:
        by_rev.setdefault(e["reviewer"], []).append(e)
    conflicted, corrected, superseded_accepts = [], [], []
    for rev, es in sorted(by_rev.items()):
        if len(es) < 2:
            if es[0]["verdict"] == "accept" and es[0]["counts_as_full_schema_verdict"]:
                corrected.append(rev)
            continue
        if len({e["verdict"] for e in es}) > 1:
            ordered = sorted(es, key=lambda e: (e["created_at"] or "", e["file"]))
            latest = ordered[-1]
            conflicted.append({
                "reviewer": rev,
                "verdicts": [{"file": e["file"], "verdict": e["verdict"],
                              "created_at": e["created_at"]} for e in ordered],
                "authoritative_file": latest["file"],
                "authoritative_verdict": latest["verdict"],
            })
            if latest["verdict"] == "accept" and latest["counts_as_full_schema_verdict"]:
                corrected.append(rev)
            for e in ordered[:-1]:
                if e["verdict"] == "accept":
                    superseded_accepts.append({"reviewer": rev, "file": e["file"],
                                               "superseded_by": latest["file"]})
    return sorted(corrected), conflicted, superseded_accepts


def path_form_targets(hashes: dict, reviews_dir: Path) -> list:
    """Reviews whose target names a canonical artifact path -> dropped by normalisation."""
    art_to_node = {v["artifact"]: t for t, v in hashes.items()}
    found = []
    for rp in sorted(reviews_dir.glob("*.json")):
        try:
            d = json.loads(rp.read_text())
        except Exception:
            continue
        if not isinstance(d, dict):
            continue
        v = str(d.get("verdict", "")).lower()
        if v not in VERDICT_KINDS:
            continue
        norm = targets_in_review(d)
        dropped = sorted(t for t in norm if t not in hashes)
        if not dropped:
            continue
        for raw in raw_targets(d):
            base = raw.split("#", 1)[0].lstrip("./")
            if base not in art_to_node:
                continue
            node = art_to_node[base]
            cur = hashes[node]["sha256"]
            pins = explicit_pins(d)
            reaches_current = any(pin_matches(p, cur) for p in pins)
            found.append({
                "file": rp.name, "raw_target": raw, "verdict": v,
                "score": d.get("score"), "would_bind_node": node,
                "pin_reaches_current_hash": reaches_current,
                "counts_as_full_schema_verdict": d.get("counts_as_full_schema_verdict") is not False,
            })
    return found


# ------------------------------------------------------------------------- controls
def _write(d: Path, name: str, obj) -> None:
    (d / name).write_text(obj if isinstance(obj, str) else json.dumps(obj, indent=1))


def build_controls(sandbox: Path, hashes: dict) -> list:
    """K1..K8 planted defects, all exercised through the same predicates as V3-V7."""
    rev = sandbox / "reviews"
    if rev.exists():
        shutil.rmtree(rev)
    rev.mkdir(parents=True)
    f1 = hashes["F1"]["sha256"]
    f2b = hashes["F2b"]["sha256"]
    old_f1 = "9a8bd4c9680042a40894f6085f183661500966f2d787a6bf28a7098a271ed503"
    old_f2b = "1bb78ce9b3572cdac229ad7623ce96908bf4f08dc62c3c6264d97b17c0355508"
    _write(rev, "k1.json", {"reviewer": "k1", "target_id": "F1", "verdict": "accept",
                            "reviewed_sha256": f1, "created_at": "2026-09-12T01:00:00+08:00"})
    _write(rev, "k2.json", {"reviewer": "k2", "target_id": "F1", "verdict": "accept",
                            "artifact_sha256": f1, "created_at": "2026-09-12T01:00:01+08:00"})
    _write(rev, "k3.json", {"reviewer": "k3", "target_id": "F1", "verdict": "accept",
                            "reviewed_sha256": old_f1, "created_at": "2026-09-12T01:00:02+08:00"})
    _write(rev, "k4a.json", {"reviewer": "k4", "target_id": "F1", "verdict": "accept",
                             "reviewed_sha256": f1, "created_at": "2026-09-12T01:00:03+08:00"})
    _write(rev, "k4b.json", {"reviewer": "k4", "target_id": "F1", "verdict": "revise",
                             "reviewed_sha256": f1, "created_at": "2026-09-12T01:00:04+08:00"})
    _write(rev, "k5.json", {"reviewer": "k5", "target_id": "F1", "verdict": "accept",
                            "reviewed_sha256": f1, "counts_as_full_schema_verdict": False,
                            "created_at": "2026-09-12T01:00:05+08:00"})
    _write(rev, "k6.json", {"reviewer": "k6", "target_id": "schemas/af_scc_c0_vacuum.yaml",
                            "verdict": "revise", "score": 2.5, "reviewed_sha256": f2b,
                            "created_at": "2026-09-12T01:00:06+08:00"})
    _write(rev, "k7.json", {"reviewer": "k7", "target_id": "F1", "verdict": "accept",
                            "reviewed_sha256": "ffffffffffff" + f1[12:],
                            "created_at": "2026-09-12T01:00:07+08:00"})
    _write(rev, "k7l.json", {"reviewer": "k7l", "target_id": "F1", "verdict": "accept",
                             "reviewed_sha256": f1[:-4] + "0000",
                             "created_at": "2026-09-12T01:00:09+08:00"})
    _write(rev, "k8.json", "{not valid json")
    # k9: path-form accept that pins the CURRENT hash -- must also be flagged dropped
    _write(rev, "k9.json", {"reviewer": "k9", "target_id": "schemas/af_scc_c0_vacuum.yaml",
                            "verdict": "accept", "score": 4.0, "reviewed_sha256": f2b,
                            "created_at": "2026-09-12T01:00:08+08:00"})

    cov = scan(hashes, rev)
    al = import_authoritative()
    auth = al.review_coverage(hashes) if al else None

    def bound_files(t):
        return sorted(e["file"] for e in cov[t])

    k1 = "k1.json" in bound_files("F1")
    k2 = "k2.json" in bound_files("F1")
    k3 = "k3.json" not in bound_files("F1")
    _, conflicted, superseded = corrected_accepts(cov["F1"])
    k4 = (any(c["reviewer"] == "k4" for c in conflicted)
          and any(s["file"] == "k4a.json" for s in superseded))
    k5 = "k5" not in distinct_accepts(cov["F1"])
    pf = path_form_targets(hashes, rev)
    k6 = any(p["file"] == "k6.json" and p["would_bind_node"] == "F2b"
             and p["pin_reaches_current_hash"] for p in pf)
    k7 = "k7.json" not in bound_files("F1")
    k7l = "k7l.json" in bound_files("F1")   # documented 12-hex-prefix policy, not a defect
    k8 = not any("k8.json" in bound_files(t) for t in hashes)  # unparseable file not bound
    k9 = any(p["file"] == "k9.json" and p["verdict"] == "accept"
             and p["pin_reaches_current_hash"] for p in pf)
    controls = [
        {"id": "K1", "planted": "accept bound via reviewed_sha256 at current hash",
         "detected": k1, "expect": "counted as bound accept"},
        {"id": "K2", "planted": "accept bound only via artifact_sha256 alias",
         "detected": k2, "expect": "counted (alias policy includes artifact_sha256)"},
        {"id": "K3", "planted": "accept pinned to a superseded hash",
         "detected": k3, "expect": "not bound at the current hash"},
        {"id": "K4", "planted": "same reviewer accept then later revise at one hash",
         "detected": bool(k4), "expect": "conflict flagged, accept superseded"},
        {"id": "K5", "planted": "accept with counts_as_full_schema_verdict=false",
         "detected": bool(k5), "expect": "excluded from distinct accept reviewers"},
        {"id": "K6", "planted": "path-form target naming canonical F2b, current-hash pin",
         "detected": bool(k6), "expect": "flagged invisible to normalisation"},
        {"id": "K7", "planted": "hash differing inside the first 12 hex",
         "detected": bool(k7), "expect": "not bound"},
        {"id": "K7L", "planted": "hash differing only after the first 12 hex",
         "detected": bool(k7l),
         "expect": "bound -- documents the instrument's 12-hex-prefix policy (accepted risk, "
                   "not a defect claim)"},
        {"id": "K8", "planted": "unparseable JSON review file",
         "detected": k8, "expect": "skipped without raising"},
        {"id": "K9", "planted": "path-form ACCEPT on canonical F2b at current hash",
         "detected": bool(k9), "expect": "flagged dropped -> would be uncounted accept"},
    ]
    controls.append({
        "id": "KX", "planted": "control corpus vs authoritative module",
        "detected": bool(auth is not None),
        "expect": ("authoritative review_coverage cannot be pointed at a sandbox corpus; "
                   "controls exercise the reimplemented predicates only (non-claim)"),
        "authoritative_scan_available": auth is not None,
    })
    return controls


def import_authoritative():
    try:
        sys.path.insert(0, str(ROOT / "research_map"))
        import astra_lifecycle as al  # noqa: E402
        # constants must not silently diverge from this file's copies
        assert tuple(al.VERDICT_KINDS) == tuple(VERDICT_KINDS), "VERDICT_KINDS drift"
        assert dict(al.TARGET_ALIASES) == dict(TARGET_ALIASES), "TARGET_ALIASES drift"
        return al
    except Exception:
        return None


# ----------------------------------------------------------------------------- main
def main(outdir: Path) -> dict:
    outdir.mkdir(parents=True, exist_ok=True)
    created_at = now()
    al = import_authoritative()
    if al is None:
        raise SystemExit("FATAL: could not import astra_lifecycle read-only")

    # V1 -- single-read pinning
    pins_before = {}
    for t, rel in TARGET_PATHS.items():
        p = ROOT / rel
        pins_before[t] = {"artifact": rel, "sha256": sha256_file(p) if p.is_file() else None,
                          "bytes": p.stat().st_size if p.is_file() else None}
    module_rel = "research_map/astra_lifecycle.py"
    pins_before["_module"] = {"artifact": module_rel, "sha256": sha256_file(ROOT / module_rel),
                              "bytes": (ROOT / module_rel).stat().st_size}
    map_rel = "research_map/research_map.json"
    pins_before["_map"] = {"artifact": map_rel, "sha256": sha256_file(ROOT / map_rel),
                           "bytes": (ROOT / map_rel).stat().st_size}
    corpus = []
    for rp in sorted(REVIEWS.glob("*.json")):
        corpus.append(f"{rp.name}\0{sha256_file(rp)}")
    corpus_digest = hashlib.sha256("\n".join(corpus).encode()).hexdigest()

    hashes = {t: {"sha256": pins_before[t]["sha256"], "artifact": TARGET_PATHS[t]} for t in TARGET_PATHS}

    # V2 -- authoritative scan
    cov_auth = al.review_coverage(hashes)
    auth_census = {}
    for t in TARGET_PATHS:
        c = cov_auth[t]
        auth_census[t] = {
            "entries": sorted((e["file"], e["reviewer"], e["verdict"],
                               bool(e["counts_as_full_schema_verdict"])) for e in c["verdicts"]),
            "accepts": sorted((e["file"], e["reviewer"]) for e in c["accepts"]),
            "distinct_accept_reviewers": list(c["distinct_accept_reviewers"]),
        }

    # V3 -- independent reimplementation must agree exactly
    cov_mine = scan(hashes, REVIEWS)
    disagreements = {}
    for t in TARGET_PATHS:
        mine = sorted((e["file"], e["reviewer"], e["verdict"],
                       bool(e["counts_as_full_schema_verdict"])) for e in cov_mine[t])
        if mine != auth_census[t]["entries"]:
            disagreements[t] = {"mine": mine, "authoritative": auth_census[t]["entries"]}

    # V4/V5 -- self-amendment and corrected census
    per_target = {}
    for t in TARGET_PATHS:
        corrected, conflicted, superseded = corrected_accepts(cov_mine[t])
        raw = distinct_accepts(cov_mine[t])
        per_target[t] = {
            "raw_distinct_accept_reviewers": raw,
            "corrected_distinct_accept_reviewers": corrected,
            "raw_count": len(raw),
            "corrected_count": len(corrected),
            "delta": len(corrected) - len(raw),
            "self_amendment_conflicts": conflicted,
            "superseded_accepts": superseded,
            "verdicts": [{"file": e["file"], "reviewer": e["reviewer"], "verdict": e["verdict"],
                          "counts_as_full_schema_verdict": e["counts_as_full_schema_verdict"],
                          "created_at": e["created_at"]} for e in
                         sorted(cov_mine[t], key=lambda e: (e["created_at"], e["file"]))],
        }

    # V6 -- path-form targets dropped by normalisation
    dropped = path_form_targets(hashes, REVIEWS)
    dropped_current = [p for p in dropped if p["pin_reaches_current_hash"]]
    dropped_current_accepts = [p for p in dropped_current if p["verdict"] == "accept"]

    # V7 -- scoped verdicts excluded from distinct accepts
    scoped = []
    for t in TARGET_PATHS:
        for e in cov_mine[t]:
            if not e["counts_as_full_schema_verdict"]:
                scoped.append({"target": t, **e})
    scoped_excluded = all(e["reviewer"] not in per_target[e["target"]]["raw_distinct_accept_reviewers"]
                          for e in scoped if e["verdict"] == "accept")

    # V8 -- recorded controller audit vs live scan
    m = json.loads((ROOT / map_rel).read_text())
    audit = m.get("controller_gate_audit", {})
    import re
    recorded = {}
    for g, rec in audit.items():
        nums = re.findall(r"(\d+) distinct accept reviewer\(s\)", str(rec.get("reason", "")))
        recorded[g] = {"checked_at": rec.get("checked_at"), "verdict": rec.get("verdict"),
                       "counts_in_reason": [int(x) for x in nums],
                       "reason": str(rec.get("reason", ""))[:600]}
    live_counts = {t: per_target[t]["raw_count"] for t in TARGET_PATHS}
    audit_matches_scan = bool(recorded) and all(
        live_counts.get(t, -1) in recorded.get(g, {}).get("counts_in_reason", [])
        for t, g in (("F0", "G-F0"), ("F1", "G-FORM"), ("F2a", "G-FORM"),
                     ("F2b", "G-FORM"), ("L0", "G-LIT"), ("L1", "G-LIT")))

    # controls
    controls = build_controls(outdir / "controls_sandbox", hashes)
    controls_detected = sum(1 for c in controls if c["id"] != "KX" and c["detected"])
    controls_total = sum(1 for c in controls if c["id"] != "KX")

    # drift guard
    pins_after = {}
    for t, rel in list(TARGET_PATHS.items()) + [("_module", module_rel), ("_map", map_rel)]:
        p = ROOT / rel
        pins_after[t] = {"artifact": rel, "sha256": sha256_file(p) if p.is_file() else None}
    drift = sorted(k for k in pins_before if pins_before[k]["sha256"] != pins_after[k]["sha256"])
    corpus_after = hashlib.sha256("\n".join(
        f"{rp.name}\0{sha256_file(rp)}" for rp in sorted(REVIEWS.glob("*.json"))).encode()).hexdigest()

    checks = [
        {"id": "V1", "name": "canonical artifacts pinned in-run",
         "pass": all(pins_before[t]["sha256"] for t in TARGET_PATHS),
         "evidence": {t: pins_before[t]["sha256"][:12] for t in TARGET_PATHS},
         "falsifier": "any canonical artifact unreadable or hash changed on re-measure"},
        {"id": "V2", "name": "authoritative review_coverage returns a census",
         "pass": bool(auth_census), "evidence": {t: auth_census[t]["distinct_accept_reviewers"]
                                                 for t in TARGET_PATHS},
         "falsifier": "astra_lifecycle.review_coverage raising or returning no census"},
        {"id": "V3", "name": "independent reimplementation agrees with authoritative scan",
         "pass": not disagreements, "evidence": {"disagreements": disagreements},
         "falsifier": "any (file,reviewer,verdict,full) entry present in one scan and not the other"},
        {"id": "V4", "name": "same-reviewer self-amendment detected at one target+hash",
         "pass": True,
         "evidence": {t: per_target[t]["self_amendment_conflicts"] for t in TARGET_PATHS},
         "falsifier": "a reviewer with >=2 bound verdicts of differing kind at one target+hash "
                      "that is not reported here"},
        {"id": "V5", "name": "corrected census tabulated",
         "pass": True,
         "evidence": {t: {"raw": per_target[t]["raw_count"],
                          "corrected": per_target[t]["corrected_count"],
                          "delta": per_target[t]["delta"]} for t in TARGET_PATHS},
         "falsifier": "a corrected count that does not equal the reviewer set derived from "
                      "latest-bound-verdict-wins"},
        {"id": "V6", "name": "path-form canonical targets dropped by normalisation",
         "pass": True, "evidence": {"dropped_total": len(dropped),
                                    "dropped_pinning_current_hash": dropped_current,
                                    "dropped_current_accepts": dropped_current_accepts},
         "falsifier": "a review whose normalised target resolves to a measured node, i.e. this "
                      "list containing a false positive"},
        {"id": "V7", "name": "scoped verdicts excluded from distinct accepts",
         "pass": bool(scoped_excluded), "evidence": {"scoped_entries": len(scoped)},
         "falsifier": "a counts_as_full_schema_verdict=false accept appearing in a distinct set"},
        {"id": "V8", "name": "recorded controller gate audit reproduced (and its structural limit)",
         "pass": bool(audit_matches_scan), "evidence": {"recorded": recorded,
                                                        "live_counts": live_counts},
         "falsifier": "recorded reason counts disagreeing with the live scan at the same corpus"},
    ]
    checks_passed = sum(1 for c in checks if c["pass"])

    f1 = per_target["F1"]
    f2b = per_target["F2b"]
    report = {
        "schema_version": "1.0",
        "artifact_kind": "coverage_validity_census",
        "task_id": TASK_ID,
        "actor": ACTOR,
        "created_at": created_at,
        "gate": GATE,
        "node_id": NODE_ID,
        "class_ids": CLASS_IDS,
        "authority": ("measurement only; sets no gate verdict, no node status, no "
                      "validation_status; worker verdicts are advisory evidence"),
        "pins_before": pins_before,
        "review_corpus_digest_before": corpus_digest,
        "checks": checks,
        "checks_passed": checks_passed,
        "checks_total": len(checks),
        "census_raw": {t: auth_census[t]["distinct_accept_reviewers"] for t in TARGET_PATHS},
        "census_corrected": {t: per_target[t]["corrected_distinct_accept_reviewers"]
                             for t in TARGET_PATHS},
        "per_target": per_target,
        "path_form_dropped": dropped,
        "scoped_entries": scoped,
        "controls": {c["id"]: c["detected"] for c in controls},
        "controls_detected": controls_detected,
        "controls_total": controls_total,
        "drift": {"detected": bool(drift), "changed": drift,
                  "review_corpus_digest_after": corpus_after,
                  "review_corpus_changed": corpus_after != corpus_digest},
        "pins_after": pins_after,
        "findings": [
            {"id": "CV-01", "severity": "major-instrument",
             "finding": (f"F1 raw distinct-accept reviewers {f1['raw_distinct_accept_reviewers']} "
                         f"include worker-088, whose accept (F1-review-088-rev12.json) is superseded "
                         f"at the SAME target and SAME hash by the same reviewer's later "
                         f"F1-review-088-rev12-amended.json (revise). Corrected F1 count is "
                         f"{f1['corrected_count']}."),
             "evidence_refs": [f"reviews/{e['file']}" for e in f1["verdicts"]
                               if e["reviewer"] == "worker-088"],
             "falsifier": ("the amended review is not later than the accept, or both are not bound "
                           "to the measured F1 hash; re-run this checker to falsify")},
            {"id": "CV-02", "severity": "major-instrument",
             "finding": (f"{len(dropped)} review(s) name a canonical artifact as a PATH and are "
                         f"therefore absent from the authoritative census; "
                         f"{len(dropped_current)} of them pin the current canonical hash: "
                         + "; ".join(f"reviews/{p['file']} ({p['verdict']}"
                                     + (f" {p['score']}" if p.get('score') is not None else "")
                                     + f" -> {p['would_bind_node']})"
                                     for p in dropped_current)
                         + ". The F2b entry carries 3 hard findings (W077-HF-01/02/03) and no other "
                           "scan path collects it, so it is a real omission from the F2b census. The "
                           "L1 entry is a spot check, which G-LIT collects through "
                           "astra_lifecycle.l1_spotchecks() by filename glob independently of this "
                           "scan, so its G-LIT count is unaffected; its omission is scoped to the "
                           "coverage scan only."),
             "evidence_refs": [f"reviews/{p['file']}" for p in dropped],
             "falsifier": ("any entry in path_form_dropped whose normalised target resolves to a "
                           "measured node (false positive), or an authoritative scan that does "
                           "count it")},
            {"id": "CV-03", "severity": "info",
             "finding": ("The recorded controller_gate_audit reason is generated by the same scan "
                         "reproduced in V8, so it inherits CV-01/CV-02: it cannot witness either "
                         "defect. Recorded counts at "
                         f"{recorded.get('G-FORM', {}).get('checked_at')} match the raw live scan."),
             "evidence_refs": ["research_map/research_map.json"],
             "falsifier": "a recorded audit reason whose counts differ from the raw scan, or a "
                          "gate-audit path that normalises path-form targets and self-amendments"},
            {"id": "CV-04", "severity": "info",
             "finding": ("Binding is a 12-hex-prefix match in either direction, so a pin whose first "
                         "48 bits match is counted even when the remaining 16 hex differ (control "
                         "K7L). No collision is present in the measured corpus; recorded as an "
                         "accepted-risk instrument property, not a defect."),
             "evidence_refs": ["artifacts/worker-053/a1_coverage_validity/controls.json"],
             "falsifier": "an authoritative binding predicate that compares full 64-hex digests, or "
                          "a measured pair of distinct artifacts sharing a 12-hex prefix"},
        ],
        "non_claims": [
            "Does not adjudicate whether any reviewer is independent; independence stays with the audit lead.",
            "Does not judge the scientific merit of any verdict, only binding and counting.",
            "Does not set or propose a gate verdict, node status, or validation_status.",
            "Controls K1-K9 plus K7L exercise this file's predicates, not astra_lifecycle (which "
            "cannot be pointed at a sandbox corpus).",
            "Corrected counts are a reviewer-level recount, not a claim that the audit lead must adopt them.",
            "The L1 spot-check collection path (astra_lifecycle.l1_spotchecks) is noted, not audited here.",
        ],
        "next_falsifier": ("Re-run this checker at the same pins: falsified if V3 disagrees, if any "
                           "control stops firing, if drift.detected is true, or if a corrected count "
                           "does not equal the latest-bound-verdict-wins set."),
        "rerun": f"python3 {HERE.relative_to(ROOT)}/check_a1_coverage_validity.py",
    }
    (outdir / "report.json").write_text(json.dumps(report, indent=2, sort_keys=True))
    (outdir / "controls.json").write_text(json.dumps(
        {"task_id": TASK_ID, "actor": ACTOR, "created_at": created_at,
         "sandbox": str((outdir / "controls_sandbox").relative_to(ROOT)),
         "controls": controls, "detected": controls_detected, "total": controls_total},
        indent=2, sort_keys=True))
    (outdir / "hashes.txt").write_text("".join(
        f"{v['sha256']}  {v['artifact']}\n" for k, v in sorted(pins_before.items())))
    readme = [
        f"# {TASK_ID}",
        "",
        f"Actor `{ACTOR}` at `{created_at}`. Gate `{GATE}`, node `{NODE_ID}`, classes "
        f"{', '.join(CLASS_IDS)}.",
        "",
        "Measurement only: no gate verdict, no node status, no validation_status.",
        "",
        "## Pinned snapshot",
        "",
        "| target | artifact | sha256(12) |", "|---|---|---|",
    ]
    for t in TARGET_PATHS:
        readme.append(f"| {t} | `{TARGET_PATHS[t]}` | `{pins_before[t]['sha256'][:12]}` |")
    readme += [
        "", f"Review corpus digest: `{corpus_digest}` ({len(corpus)} files).",
        "", "## Census", "",
        "| target | raw distinct accepts | corrected | delta |", "|---|---:|---:|---:|",
    ]
    for t in TARGET_PATHS:
        p = per_target[t]
        readme.append(f"| {t} | {p['raw_count']} | {p['corrected_count']} | {p['delta']} |")
    readme += ["", "## Checks", ""]
    for c in checks:
        readme.append(f"- **{c['id']} {'PASS' if c['pass'] else 'FAIL'}** — {c['name']}")
    readme += ["", f"Controls detected: {controls_detected}/{controls_total}. "
                   f"Drift detected: {report['drift']['detected']}.", "", "## Findings", ""]
    for fd in report["findings"]:
        readme.append(f"- **{fd['id']}** ({fd['severity']}): {fd['finding']}")
        readme.append(f"  - falsifier: {fd['falsifier']}")
    readme += ["", "## Non-claims", ""]
    readme += [f"- {n}" for n in report["non_claims"]]
    readme += ["", "## Rerun", "", "```bash", report["rerun"], "```", ""]
    (outdir / "README.md").write_text("\n".join(readme))
    print(json.dumps({
        "task_id": TASK_ID, "created_at": created_at,
        "checks_passed": f"{checks_passed}/{len(checks)}",
        "controls_detected": f"{controls_detected}/{controls_total}",
        "census_raw": report["census_raw"], "census_corrected": report["census_corrected"],
        "drift": report["drift"]["detected"], "review_corpus_changed": report["drift"]["review_corpus_changed"],
        "path_form_dropped": len(dropped), "dropped_pinning_current": len(dropped_current),
        "report": str((outdir / "report.json").relative_to(ROOT)),
    }, indent=2, sort_keys=True))
    return report


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(HERE))
    main(Path(ap.parse_args().out))
