#!/usr/bin/env python3
"""W067-A2-BUDGETMATCH-01 — independent, read-only budget-matching audit of the A2 pin.

Task (worker-067, one bounded class-bound task; A2 spans the four frozen classes
AF-WCC-VAC-GEN / AF-SCC-C2-VAC-GEN / AF-SCC-C0-VAC-GEN / AF-WCC-SCALAR-SPH):

  At the map-declared A2 pin ``evaluation/ablation.csv#ee3aa6cb97d0`` and its companion
  ``evaluation/ablation_report.json#d7e1cd15abef``, generated by the pinned harness
  ``evaluation/ablation_harness.py#df878e97bf6e`` under the frozen design
  ``evaluation/ablation_design.yaml#1b2a83ef670b``:

  T1  do the two pinned artifacts agree with each other on every shared field?
  T2  do the report's internal arithmetic identities hold (rates, cost, calls, per-class)?
  T3  does an independent in-process re-run of the pinned harness reproduce the report?
  T4  does the pinned budget check implement the design's pre-registered matching rule
      (tokens AND wall-clock, +/-2%), or a looser/different one?
  T5  what is the measured wall-clock consumption spread across the four primary arms,
      and does the pinned ``check_matched_budgets`` test it at all?
  T6  is ``primary_comparison_valid: true`` stable under the design's literal falsifier?

Authority: worker-level artifact/checker evidence only.  No gate verdict, no node
transition, no canonical-path write, no numerics work.  The checker pins every input by
full sha256 and exits 2 (fail-closed) on any drift.  It writes only ``report.json`` next
to itself.

Run:  python3 check_a2_budgetmatch.py [--report PATH]
Exit: 0 = checks reproduced / findings established; 1 = internal contradiction; 2 = pin
drift (fail-closed).
"""
from __future__ import annotations

import argparse
import ast
import csv
import hashlib
import importlib.util
import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent

PINS = {
    "evaluation/ablation.csv":
        "ee3aa6cb97d0871a526102654fb9a793680c9f7e4f0ef3958b0a8db3648e8d45",
    "evaluation/ablation_report.json":
        "d7e1cd15abef5db56be8211ec512d00bd14dd0163cfc2793b6f10e6e25639e5a",
    "evaluation/ablation_design.yaml":
        "1b2a83ef670b7e757a1a54d4849b49a597d5dc33e9205c0b5b10646d811cfb0a",
    "evaluation/ablation_harness.py":
        "df878e97bf6ede6c41e540dcf20664e51c9963cf44d74c2f5f9a9005bc8af432",
}
CLASS_IDS = ["AF-WCC-VAC-GEN", "AF-SCC-C2-VAC-GEN", "AF-SCC-C0-VAC-GEN", "AF-WCC-SCALAR-SPH"]
# Design reading, recorded as an assumption and bound to the design text below:
#   "All arms receive the same total completion-token budget B (+/-2%) and the same
#    wall-clock envelope T (+/-2%)"  (budget_matching.rule)
#   "all arms matched within 2% on tokens and wall-clock"  (endpoints.hypotheses.H-design)
DESIGN_TOLERANCE = 0.02
PIN_TOLERANCE = 0.15  # the tolerance actually recorded in the pinned report's config
ARM_FIELDS = [
    "is_primary", "is_null", "token_budget", "wall_budget", "tokens_consumed",
    "wall_consumed", "stop_reason", "episodes_attempted", "calls", "accepted",
    "rejected", "hard_failures", "claims_emitted", "accepted_claim_rate",
    "hard_failure_rate", "citation_support", "duplication", "reviewer_agreement",
    "novel_accepted_coverage", "cost_per_accepted_claim",
]


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_pins(pins: dict[str, str]) -> dict:
    measured, drifted = {}, []
    for rel, want in pins.items():
        p = ROOT / rel
        if not p.exists():
            drifted.append({"path": rel, "reason": "missing", "expected": want})
            continue
        got = sha256_file(p)
        measured[rel] = got
        if got != want:
            drifted.append({"path": rel, "reason": "hash_mismatch",
                            "expected": want, "measured": got})
    return {"ok": not drifted, "measured": measured, "drifted": drifted}


def load_json(rel: str):
    return json.loads((ROOT / rel).read_text())


def load_csv(rel: str) -> list[dict]:
    with (ROOT / rel).open(newline="") as f:
        return list(csv.DictReader(f))


def as_bool(v) -> bool:
    return str(v).strip().lower() in ("true", "1", "yes")


def as_float(v):
    if v is None or v == "":
        return None
    return float(v)


def close(a, b, tol=1e-9) -> bool:
    if a is None or b is None:
        return a is b
    return abs(a - b) <= tol


# ---------------------------------------------------------------------------
# T1  CSV <-> report agreement
# ---------------------------------------------------------------------------

def t1_csv_report_agreement(rows: list[dict], report: dict) -> dict:
    arms = {a["arm"]: a for a in report["arms"]}
    mismatches = []
    if len(rows) != len(report["arms"]):
        mismatches.append(f"row count {len(rows)} != arm count {len(report['arms'])}")
    for r in rows:
        arm = arms.get(r["arm"])
        if arm is None:
            mismatches.append(f"csv arm {r['arm']} absent from report")
            continue
        for f in ARM_FIELDS:
            if f not in r or f not in arm:
                mismatches.append(f"{r['arm']}.{f}: field absent")
                continue
            cv, rv = r[f], arm[f]
            if f in ("is_primary", "is_null"):
                if as_bool(cv) != bool(rv):
                    mismatches.append(f"{r['arm']}.{f}: csv={cv} report={rv}")
            elif f == "stop_reason":
                if cv != rv:
                    mismatches.append(f"{r['arm']}.{f}: csv={cv} report={rv}")
            else:
                if not close(as_float(cv), as_float(rv), 1e-9):
                    mismatches.append(f"{r['arm']}.{f}: csv={cv} report={rv}")
        pcc = json.loads(r["per_class_coverage"])
        if pcc != arm["per_class_coverage"]:
            mismatches.append(f"{r['arm']}.per_class_coverage csv/report differ")
    return {"name": "T1_csv_report_agreement", "pass": not mismatches,
            "detail": f"{len(rows)} rows x {len(ARM_FIELDS)} fields compared",
            "mismatches": mismatches}


# ---------------------------------------------------------------------------
# T2  internal arithmetic identities
# ---------------------------------------------------------------------------

def t2_arithmetic_identities(rows: list[dict]) -> dict:
    fails = []
    per_class_counts = {}
    for r in rows:
        arm, attempts, accepted = r["arm"], int(r["episodes_attempted"]), int(r["accepted"])
        if not close(as_float(r["accepted_claim_rate"]), accepted / attempts):
            fails.append(f"{arm}: accepted_claim_rate != accepted/episodes_attempted")
        if not close(as_float(r["hard_failure_rate"]), int(r["hard_failures"]) / attempts):
            fails.append(f"{arm}: hard_failure_rate != hard_failures/episodes_attempted")
        if not close(as_float(r["novel_accepted_coverage"]), accepted / 60):
            fails.append(f"{arm}: novel_accepted_coverage != accepted/60")
        if accepted and not close(as_float(r["cost_per_accepted_claim"]),
                                  as_float(r["tokens_consumed"]) / accepted):
            fails.append(f"{arm}: cost_per_accepted_claim != tokens_consumed/accepted")
        samples = {"single": 1, "null": 1}.get(r["kind"], 5)
        if int(r["calls"]) != attempts * samples:
            fails.append(f"{arm}: calls != episodes_attempted x samples({samples})")
        if int(r["calls"]) - int(r["claims_emitted"]) != int(r["hard_failures"]):
            # each invalid call costs one claim slot; harness counts hard failures from None finals
            pass  # not an identity for the coordinated arms; recorded, not asserted
        pcc = json.loads(r["per_class_coverage"])
        counts = {k: round(v * 15) for k, v in pcc.items()}
        for k, v in pcc.items():
            if not close(v, counts[k] / 15, 1e-9):
                fails.append(f"{arm}: per_class_coverage[{k}]={v} is not n/15")
        if sum(counts.values()) != accepted:
            fails.append(f"{arm}: per-class integer counts {sum(counts.values())} != accepted {accepted}")
        per_class_counts[arm] = counts
    return {"name": "T2_arithmetic_identities", "pass": not fails,
            "detail": "rates, cost, calls and per-class n/15 reconstruction", "fails": fails,
            "per_class_counts": per_class_counts}


# ---------------------------------------------------------------------------
# T3  independent re-run of the pinned harness
# ---------------------------------------------------------------------------

def _import_pinned_harness():
    rel = "evaluation/ablation_harness.py"
    p = ROOT / rel
    if sha256_file(p) != PINS[rel]:
        raise SystemExit("PIN DRIFT: refusing to import harness at unexpected bytes")
    spec = importlib.util.spec_from_file_location("w067_pinned_a2_harness", p)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod  # dataclasses need the module registered before exec
    spec.loader.exec_module(mod)
    return mod


def _strip_generated(d: dict) -> dict:
    return {k: v for k, v in d.items() if k != "generated_at"}


def t3_reproduce(rows: list[dict], report: dict) -> dict:
    mod = _import_pinned_harness()
    cfg = dict(report["config"])
    rerun = mod.run_ablation(cfg)
    same_report = _strip_generated(rerun) == _strip_generated(report)
    # CSV is written from a second, independent set of run_arm calls in the harness CLI
    eps = mod.build_episodes(cfg["episodes"])
    arms = mod.synthetic_arms()
    models = mod.synthetic_models()
    results = [mod.run_arm(a, eps, models, token_budget=cfg["token_budget"],
                           wall_budget=cfg["wall_budget"], seed=cfg["seed"],
                           reviewer_error_rate=cfg["reviewer_error_rate"]) for a in arms]
    csv_arm = {a["arm"]: a for a in (mod.arm_result_dict(r) for r in results)}
    csv_rows = {r["arm"]: r for r in rows}
    csv_same = True
    csv_diff = []
    for arm, a in csv_arm.items():
        r = csv_rows[arm]
        for f in ARM_FIELDS:
            if f == "stop_reason":
                ok = r[f] == a[f]
            elif f in ("is_primary", "is_null"):
                ok = as_bool(r[f]) == bool(a[f])
            else:
                ok = close(as_float(r[f]), as_float(a[f]), 1e-9)
            if not ok:
                csv_same = False
                csv_diff.append(f"{arm}.{f}: disk={r[f]} rerun={a[f]}")
    return {"name": "T3_reproduce_pinned_harness", "pass": bool(same_report and csv_same),
            "detail": "run_ablation(pin config) and CLI-equivalent arm runs vs pinned bytes",
            "report_reproduced": same_report, "csv_reproduced": csv_same,
            "csv_diffs": csv_diff,
            "generator_sha256_declared": report["generator_sha256"],
            "generator_sha256_measured": sha256_file(ROOT / "evaluation/ablation_harness.py")}


# ---------------------------------------------------------------------------
# T4/T5/T6  budget-matching rule vs implementation
# ---------------------------------------------------------------------------

def _spread(values: list[float], denominator: float) -> float:
    return (max(values) - min(values)) / denominator


def t4_t5_t6(rows: list[dict], report: dict) -> dict:
    primary = [r for r in rows if as_bool(r["is_primary"])]
    caps = {(as_float(r["token_budget"]), as_float(r["wall_budget"])) for r in primary}
    tokens = [as_float(r["tokens_consumed"]) for r in primary]
    walls = [as_float(r["wall_consumed"]) for r in primary]
    token_spread = _spread(tokens, primary[0]["token_budget"] and as_float(primary[0]["token_budget"]) or 1.0)
    wall_spread_of_max = _spread(walls, max(walls))
    wall_spread_of_envelope = _spread(walls, as_float(primary[0]["wall_budget"]))

    # T4: which tolerance did the pin actually apply, and was the design override recorded?
    design_text = (ROOT / "evaluation/ablation_design.yaml").read_text()
    design_2pct_present = bool(re.search(r"\+/-2%|within 2%", design_text))
    pin_cfg = report["config"]
    t4 = {
        "name": "T4_design_tolerance_conformance",
        "pass": bool(design_2pct_present and close(pin_cfg.get("token_tolerance"), DESIGN_TOLERANCE)),
        "detail": ("design pre-registers +/-2% and expects the design to override defaults; "
                   "pin records token_tolerance"),
        "design_2pct_text_present": design_2pct_present,
        "design_tolerance": DESIGN_TOLERANCE,
        "pin_token_tolerance": pin_cfg.get("token_tolerance"),
        "pin_matched": report["budget_check"]["matched"],
        "pin_reported_token_spread": report["budget_check"]["token_spread_fraction"],
        "design_override_recorded": any(k in report for k in ("design_ref", "design_sha256")),
    }

    # T5: is there any wall-clock-consumption matching test in the pinned checker?
    harness_src = (ROOT / "evaluation/ablation_harness.py").read_text()
    tree = ast.parse(harness_src)
    fn = next((n for n in ast.walk(tree)
               if isinstance(n, ast.FunctionDef) and n.name == "check_matched_budgets"), None)
    wall_max_min = False
    wall_attrs = []
    if fn is not None:
        for n in ast.walk(fn):
            if isinstance(n, ast.Attribute) and n.attr == "wall_consumed":
                wall_attrs.append(n.lineno)
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Name) and n.func.id in ("max", "min"):
                for arg in n.args:
                    if isinstance(arg, (ast.ListComp, ast.GeneratorExp)):
                        seg = ast.dump(arg)
                        if "wall_consumed" in seg:
                            wall_max_min = True
    t5 = {
        "name": "T5_wall_clock_matching_test_present",
        "pass": wall_max_min,
        "detail": "AST scan of pinned check_matched_budgets for a max/min over wall_consumed",
        "wall_consumed_reference_lines": wall_attrs,
        "wall_spread_test_present": wall_max_min,
        "primary_wall_consumed": walls,
        "primary_tokens_consumed": tokens,
        "primary_caps": sorted(caps),
        "wall_spread_of_max": wall_spread_of_max,
        "wall_spread_of_envelope": wall_spread_of_envelope,
        "token_spread_of_budget": token_spread,
        "all_primary_token_limited": all(r["stop_reason"] == "token_budget" for r in primary),
    }

    # T6: stability of primary_comparison_valid under the design's two readings.
    # Envelope reading: every arm receives the same wall-clock cap (caps identical).
    # Consumption reading: measured wall-clock consumed is matched within tolerance.
    envelope_ok = len(caps) == 1
    consumption_ok = wall_spread_of_max <= DESIGN_TOLERANCE
    t6 = {
        "name": "T6_primary_comparison_valid_stability",
        "pass": bool(report["primary_comparison_valid"] == (token_spread <= DESIGN_TOLERANCE
                                                            and envelope_ok)),
        "detail": ("pin says primary_comparison_valid=%s; under the envelope reading the design "
                   "rule holds trivially, under the consumption reading it is void"
                   % report["primary_comparison_valid"]),
        "token_rule_holds": token_spread <= DESIGN_TOLERANCE,
        "envelope_reading_holds": envelope_ok,
        "consumption_reading_holds": consumption_ok,
        "pin_primary_comparison_valid": report["primary_comparison_valid"],
        "design_waived_wallclock_clause": not consumption_ok,
    }
    return t4, t5, t6


# ---------------------------------------------------------------------------
# controls
# ---------------------------------------------------------------------------

def controls(rows: list[dict], report: dict) -> list[dict]:
    out = []

    # C1: mutate one CSV numeric leaf; the arithmetic identity must catch it
    mut = [dict(r) for r in rows]
    for r in mut:
        if r["arm"] == "independent_cheap":
            r["tokens_consumed"] = str(as_float(r["tokens_consumed"]) + 100)
    c1 = t2_arithmetic_identities(mut)
    out.append({"id": "C1_mutation_detected", "pass": not c1["pass"],
                "detail": "tokens_consumed +100 on independent_cheap breaks cost identity",
                "caught": c1["fails"][:3]})

    # C2: tolerance provenance is material: a 5% spread passes at 0.15, fails at 0.02
    out.append({"id": "C2_tolerance_materiality", "pass": (0.05 <= PIN_TOLERANCE
                                                           and 0.05 > DESIGN_TOLERANCE),
                "detail": "5% spread accepted by pin tolerance 0.15, rejected by design 0.02",
                "pin_accepts_5pct": 0.05 <= PIN_TOLERANCE,
                "design_accepts_5pct": 0.05 <= DESIGN_TOLERANCE})

    # C3: fail-closed on hash drift
    bad = dict(PINS)
    bad["evaluation/ablation.csv"] = "0" * 64
    drift = verify_pins(bad)
    out.append({"id": "C3_fail_closed_on_drift", "pass": not drift["ok"],
                "detail": "a wrong pin is rejected rather than ignored",
                "drifted": drift["drifted"]})

    # C4: no-write canary is evaluated by the caller after the report is written
    return out


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--report", default=str(HERE / "report.json"))
    a = ap.parse_args(argv)

    pins_before = verify_pins(PINS)
    if not pins_before["ok"]:
        print(json.dumps({"verdict": "PIN_DRIFT_FAIL_CLOSED", "drifted": pins_before["drifted"]},
                         indent=2))
        return 2

    rows = load_csv("evaluation/ablation.csv")
    report = load_json("evaluation/ablation_report.json")
    design_text = (ROOT / "evaluation/ablation_design.yaml").read_text()

    t1 = t1_csv_report_agreement(rows, report)
    t2 = t2_arithmetic_identities(rows)
    t3 = t3_reproduce(rows, report)
    t4, t5, t6 = t4_t5_t6(rows, report)
    ctrl = controls(rows, report)

    findings = [
        {
            "id": "W067-A2-F1",
            "rubric": "HF-11",
            "severity": "major",
            "status": "OPEN_AT_PIN",
            "statement": (
                "The pinned harness's check_matched_budgets contains no wall-clock-consumption "
                "matching test, while the pinned design pre-registers token and wall-clock "
                "matching at +/-2% (H-design). At the pin the four primary arms consumed "
                "wall_clock 30.0/30.0/24.75/24.8 (spread 17.5% of max, 8.75% of the 60 s "
                "envelope), so under the consumption reading the design's own falsifier fires "
                "and primary_comparison_valid=true is void. Under the envelope reading the "
                "clause is satisfied trivially by identical caps."),
            "evidence": [
                "evaluation/ablation.csv#ee3aa6cb97d0",
                "evaluation/ablation_report.json#d7e1cd15abef",
                "evaluation/ablation_harness.py#df878e97bf6e check_matched_budgets",
                "evaluation/ablation_design.yaml#1b2a83ef670b budget_matching.rule / H-design",
                "artifacts/worker-067/a2_budgetmatch/report.json (T5/T6)",
            ],
            "owner_action": "design owner disambiguates envelope vs consumption; harness adds the "
                            "wall-clock spread test (or the design drops the consumption clause "
                            "and records the envelope-only reading) before any A2 accept",
        },
        {
            "id": "W067-A2-F2",
            "rubric": "HF-11",
            "severity": "major",
            "status": "OPEN_AT_PIN",
            "statement": (
                "The pin records config.token_tolerance=0.15 (the harness default) while the "
                "design pre-registers +/-2% (0.02), and no design override/reference is recorded "
                "in the report, so budget_check.matched=true was computed against a tolerance "
                "7.5x looser than the pre-registered one. The measured token spread (1%) passes "
                "both, so the boolean happens to agree, but the recorded check does not implement "
                "the design rule it is cited for."),
            "evidence": [
                "evaluation/ablation_report.json#d7e1cd15abef config.token_tolerance",
                "evaluation/ablation_harness.py#df878e97bf6e DEFAULTS token_tolerance 0.15",
                "evaluation/ablation_design.yaml#1b2a83ef670b budget_matching.rule (+/-2%)",
                "artifacts/worker-067/a2_budgetmatch/report.json (T4, C2)",
            ],
            "owner_action": "record design_ref/design_sha256 in the report and run with the design's "
                            "2% tolerance (or amend the design with a reason)",
        },
        {
            "id": "W067-A2-F3",
            "rubric": "HF-08",
            "severity": "minor",
            "status": "NOTE_AT_PIN",
            "statement": (
                "The pin is reproducible: an independent in-process run of the pinned harness at "
                "the pin's recorded config reproduces the report on every leaf except "
                "generated_at, and the CLI-equivalent arm runs reproduce the CSV. The pin does "
                "not itself record the command/exit code, so reproducibility rests on the README "
                "command plus the recorded generator_sha256/config."),
            "evidence": [
                "artifacts/worker-067/a2_budgetmatch/report.json (T3)",
                "evaluation/README_ablation_harness.md",
            ],
            "owner_action": "optional: record command and exit code in the report",
        },
    ]

    checks = [t1, t2, t3, t4, t5, t6] + ctrl
    def _is_invariant(c):
        return str(c.get("name", "")).startswith(("T1", "T2", "T3", "T6")) or str(c.get("id", "")).startswith("C")
    invariants = [c for c in checks if _is_invariant(c)]
    probes = [t4, t5]
    invariants_ok = all(c["pass"] for c in invariants)
    probes_triggered = all(not c["pass"] for c in probes)
    internal_ok = t1["pass"] and t2["pass"] and t3["pass"]
    verdict = "REVISE_HF11_AT_PIN" if internal_ok else "INTERNAL_CONTRADICTION"

    # C4 no-write canary
    pins_after = verify_pins(PINS)
    canary = {"id": "C4_no_write_canary", "pass": pins_after["measured"] == pins_before["measured"],
              "detail": "all four pinned inputs re-hash identically after the run"}
    checks.append(canary)
    invariants.append(canary)
    invariants_ok = invariants_ok and canary["pass"]

    doc = {
        "task_id": "W067-A2-BUDGETMATCH-01",
        "node_id": "A2",
        "gate": "G-AUDIT",
        "class_ids": CLASS_IDS,
        "authority": "worker-level artifact/checker evidence only; not a gate verdict, "
                     "not a node transition, no canonical-path write",
        "actor": "worker-067",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "verdict": verdict,
        "all_invariants_pass": invariants_ok,
        "finding_probes_triggered": probes_triggered,
        "pins": pins_before["measured"],
        "design_readings": {
            "design_tolerance_assumed": DESIGN_TOLERANCE,
            "pin_tolerance_measured": report["config"].get("token_tolerance"),
            "envelope_reading_matched": t6["envelope_reading_holds"],
            "consumption_reading_matched": t6["consumption_reading_holds"],
            "design_text_quote": "(+/-2%) tokens and wall-clock; matched_fields includes wall_clock_s",
        },
        "checks": checks,
        "findings": findings,
        "not_claimed": [
            "not a gate verdict; workers cannot pass G-AUDIT or set A2 done",
            "no canonical path was written; the design, harness, CSV and report are read-only",
            "no model call was made; the engine is the synthetic dry-run",
            "no claim about real model behaviour or swarm advantage",
        ],
        "falsifier": (
            "Withdrawn if any pinned input hash moves; or if a re-run of the pinned harness "
            "does not reproduce the pinned report/CSV; or if check_matched_budgets is shown to "
            "test wall-clock consumption spread (AST or execution); or if the design text is "
            "amended to an envelope-only reading at a new hash that voids this pin."),
    }
    out = Path(a.report)
    out.write_text(json.dumps(doc, indent=2, sort_keys=True))
    print(json.dumps({"verdict": verdict, "all_invariants_pass": invariants_ok,
                      "finding_probes_triggered": probes_triggered,
                      "report": str(out), "findings": [f["id"] for f in findings]}, indent=2))
    return 0 if internal_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
