#!/usr/bin/env python3
"""Generate the WP13-F1-GATE reject corpus deterministically from the conforming fixture.

Each mutation changes exactly one class-bound obligation so the expected failing rule is
predictable. Run: python3 make_fixtures.py   (writes fixtures/*.yaml next to the source).
"""
from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
FIX = HERE / "fixtures"
SOURCE = FIX / "valid_af_wcc_vac_gen.yaml"

# case -> (mutation function, expected gate verdict, expected rule ids, note)
EXPECT = {
    "leak_scc_c2": ("reject", ["R09"], "strong-censorship content imported into the weak class"),
    "leak_scalar_sph": ("reject", ["R05", "R09"], "scalar-field / spherical-symmetry content and non-vacuum matter"),
    "vague_quantifiers": ("reject", ["R03"], "quantifier order deleted; formal statement left unquantified"),
    "conclusion_inflation": ("reject", ["R08"], "conclusion_type inflated to theorem + numerical evidence phrase"),
    "vague_data_class": ("reject", ["R05"], "weighted data class replaced by vague qualifiers"),
    "missing_falsifier": ("reject", ["R10"], "falsifier emptied to none/n-a"),
    "probe_rephrased_leak": ("accept", [], "KNOWN BLIND SPOT: SCC content rephrased to avoid R09 tokens"),
}


def mutate(name: str, d: dict) -> dict:
    d = copy.deepcopy(d)
    d["fixture"] = True
    d["fixture_expectation"] = EXPECT[name][0]
    d["mutation_note"] = EXPECT[name][2]
    if name == "leak_scc_c2":
        d["conclusion_type"] = "conditional_theorem"
        d["assumptions"].append(
            "the maximal development is C^2-inextendible beyond the Cauchy horizon"
        )
    elif name == "leak_scalar_sph":
        d["data_class"]["matter"] = "self-gravitating scalar field"
        d["data_class"]["constraints"].append("Klein-Gordon equation")
        d["assumptions"].append("spherical symmetry is imposed on the initial data")
    elif name == "vague_quantifiers":
        d["quantifier_order"] = []
        d["formal_statement"] = "Generically one expects that a singularity, if it forms, is hidden."
    elif name == "conclusion_inflation":
        d["conclusion_type"] = "theorem"
        d["conclusion"] = (
            "A maximal development exists for every data set in DataClass, and numerical "
            "evidence confirms the singularity is hidden."
        )
    elif name == "vague_data_class":
        d["data_class"]["weight"] = "sufficiently decaying"
        d["data_class"]["decay_rate"] = "suitable"
        d["data_class"]["norm"] = "appropriate"
        d["data_class"]["sobolev_index"] = "appropriate"
    elif name == "missing_falsifier":
        d["falsifier"] = {"witness_type": "none", "test": "n/a"}
    elif name == "probe_rephrased_leak":
        d["conclusion_type"] = "conditional_theorem"
        d["assumptions"].append(
            "the maximal development is continuously extendible past the horizon, so the "
            "relevant question is extendibility rather than visibility"
        )
    else:  # pragma: no cover
        raise SystemExit(f"unknown mutation {name}")
    return d


def main() -> int:
    src = yaml.safe_load(SOURCE.read_text())
    manifest = {}
    for name, (verdict, rules, note) in EXPECT.items():
        doc = mutate(name, src)
        out = FIX / f"{name}.yaml"
        out.write_text(
            "# GENERATED by make_fixtures.py from valid_af_wcc_vac_gen.yaml — do not hand-edit.\n"
            + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)
        )
        manifest[name] = {
            "path": str(out),
            "expected_verdict": verdict,
            "expected_failed_rules": rules,
            "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
            "note": note,
        }
    (FIX / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {len(manifest)} fixtures from {SOURCE.name}")
    for name, m in manifest.items():
        print(f"  {name:24s} expect={m['expected_verdict']:6s} rules={','.join(m['expected_failed_rules']) or '-'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
